<template lang="pug">
.container
  .page-title 
    h2 Deklination der Adjektive
  Tabs(:items= 'Nominativ' title='Nominativ' )
  Tabs(:items= 'Akkusativ' title='Akkusativ' )
  Tabs(:items= 'Dativ' title='Dativ' )
  Tabs(:items= 'Genitiv' title='Genitiv' )
  .page-block
    .page-title--small 
      h2 Training 
    TabsTraining( title='Nominativ' :SlotData='SlotDataNominativ' )
</template>


<script setup>
import Tabs from '@/components/Tabs.vue';
import TabsTraining from '@/components/TabsTraining.vue';



const SlotDataNominativ = [

  {
    t0: 'Красная машина принадлежит богатому человеку.(Auto gehört Mann)',
    t1: 'Das',
    t2: 'rote',
    t3: 'Auto',
    t4: 'gehört',
    t5: 'dem',
    t6: 'reichen',
    t7: 'Mann',
    t8: '.',
  },
  {
    t0: 'Ганс сидит на старом диване.(Hans Sofa)',
    t1: 'Hans',
    t2: 'sitzt',
    t3: 'auf',
    t4: 'dem',
    t5: 'alten',
    t6: 'Sofa',
    t7: '.',
  },
  {
    t0: 'Дом стоит рядом с большим парком.(Haus Park)',
    t1: 'Das',
    t2: 'Haus',
    t3: 'steht',
    t4: 'neben',
    t5: 'dem',
    t6: 'großen',
    t7: 'Park',
    t8: '.',
  },
  {
    t0: 'Маленький домик серый.(Haus)',
    t1: 'Das',
    t2: 'kleine',
    t3: 'Haus',
    t4: 'ist',
    t5: 'grau',
    t6: '.',
  },
  {
    t0: 'Моя новая машина стоит в гараже.(Garage)',
    t1: 'Mein',
    t2: 'neues',
    t3: 'Auto',
    t4: 'steht',
    t5: 'in',
    t6: 'der',
    t7: 'Garage',
    t8: '.',
  },
  {
    t0: 'Ганс сидит на старом ящике.(Hans Kiste)',
    t1: 'Hans',
    t2: 'sitzt',
    t3: 'auf',
    t4: 'einer',
    t5: 'alten',
    t6: 'Kiste',
    t7: '.',
  },
  {
    t0: 'Дом не в хорошем состоянии.(Zustand)',
    t1: 'Das',
    t2: 'Haus',
    t3: 'ist',
    t4: 'in',
    t5: 'keinem',
    t6: 'guten',
    t7: 'Zustand',
    t8: '.',
  },
  {
    t0: 'Это узкая кровать.(Bett)',
    t1: 'Das',
    t2: 'ist',
    t3: 'ein',
    t4: 'schmales',
    t5: 'Bett',
    t6: '.',
  },
  {
    t0: 'Молодые женщины часто бывают очень красивыми.(hübsch)',
    t1: 'Junge',
    t2: 'Frauen',
    t3: 'sind',
    t4: 'oft',
    t5: 'sehr',
    t6: 'hübsch',
    t7: '.',
  },
  {
    t0: 'Немец выпивает каждый год 130 литров холодного пива.(Deutscher jedes 130 Liter)',
    t1: 'Ein',
    t2: 'Deutscher',
    t3: 'trinkt',
    t4: 'jedes',
    t5: 'Jahr',
    t6: '130',
    t7: 'Liter',
    t8: 'kaltes',
    t9: 'Bier',
    t10: '.',
  },
  {
    t0: 'Кольцо из чистого золота.(Ring purem Gold)',
    t1: 'Der',
    t2: 'Ring',
    t3: 'ist',
    t4: 'aus',
    t5: 'purem',
    t6: 'Gold',
    t7: '.',
  },
  {
    t0: 'Там стоят красные машины.(Dort)',
    t1: 'Dort',
    t2: 'stehen',
    t3: 'rote',
    t4: 'Autos',
    t5: '.',
  },
  {
    t0: 'Это высокая башня.(Turm)',
    t1: 'Das',
    t2: 'ist',
    t3: 'ein',
    t4: 'hoher',
    t5: 'Turm',
    t6: '.',
  },
  {
    t0: 'Это розовое платье.(Kleid)',
    t1: 'Das',
    t2: 'ist',
    t3: 'ein',
    t4: 'rosa',
    t5: 'Kleid',
    t6: '.',
  },
  {
    t0: 'Фиолетовая блузка уродлива.(hässlich)',
    t1: 'Die',
    t2: 'lila',
    t3: 'Bluse',
    t4: 'ist',
    t5: 'hässlich',
    t6: '.',
  },
  {
    t0: 'Франкфуртский аэропорт огромен.(Frankfurter Flughafen)',
    t1: 'Der',
    t2: 'Frankfurter',
    t3: 'Flughafen',
    t4: 'ist',
    t5: 'riesig',
    t6: '.',
  },
  {
    t0: 'Лучший друг нашел новую работу.()',
    t1: 'Der',
    t2: 'beste',
    t3: 'Freund',
    t4: 'hat',
    t5: 'einen',
    t6: 'neuen',
    t7: 'Job',
    t8: 'gefunden',
    t9: '.',
  },
  {
    t0: 'Ему нравится играть с милыми собачками.(süßen Hunden)',
    t1: 'Er',
    t2: 'spielt',
    t3: 'gerne',
    t4: 'mit',
    t5: 'den',
    t6: 'süßen',
    t7: 'Hunden',
    t8: '.',
  },
  {
    t0: 'У коллеги зеленые глаза, маленький нос и длинная борода.(Kollege Nase Bart)',
    t1: 'Der',
    t2: 'Kollege',
    t3: 'hat',
    t4: 'grüne',
    t5: 'Augen',
    t6: ',',
    t7: 'eine',
    t8: 'kleine',
    t9: 'Nase',
    t10: 'und',
    t11: 'einen',
    t12: 'langen',
    t13: 'Bart',
    t14: '.',
  },
  {
    t0: 'Хенрих находит старые фильмы очень интересными.(Filme Henrich)',
    t1: 'Alte',
    t2: 'Filme',
    t3: 'findet',
    t4: 'Henrich',
    t5: 'sehr',
    t6: 'interessant',
    t7: '.',
  },
  {
    t0: 'Генрих в настоящее время живет в огромном доме, принадлежащем его богатой семье.(Henrich zurzeit wohlhabenden Familie)',
    t1: 'Henrich',
    t2: 'wohnt',
    t3: 'zurzeit',
    t4: 'in',
    t5: 'einem',
    t6: 'riesigen',
    t7: 'Haus',
    t8: 'seiner',
    t9: 'wohlhabenden',
    t10: 'Familie',
    t11: '.',
  },
  {
    t0: 'Сабрина скоро выходит замуж и хочет отпраздновать в этом неизвестном месте.(Sabrina Lokal feiern)',
    t1: 'Sabrina',
    t2: 'heiratet',
    t3: 'bald',
    t4: 'und',
    t5: 'will',
    t6: 'in',
    t7: 'diesem',
    t8: 'unbekannten',
    t9: 'Lokal',
    t10: 'feiern',
    t11: '.',
  },
  {
    t0: 'Это место гордится своим великим прошлым.(Platz stolz Vergangenheit)',
    t1: 'Dieser',
    t2: 'Platz',
    t3: 'ist',
    t4: 'stolz',
    t5: 'auf',
    t6: 'seine',
    t7: 'große',
    t8: 'Vergangenheit',
    t9: '.',
  },
  {
    t0: 'Ребекка полностью забыла всю итальянскую лексику.(Rebekka Vokabeln total vergessen)',
    t1: 'Rebekka',
    t2: 'hat',
    t3: 'alle',
    t4: 'italienischen',
    t5: 'Vokabeln',
    t6: 'total',
    t7: 'vergessen',
    t8: '.',
  },
  {
    t0: 'Как вы планируете ваше предстоящее выздоровление?(Wonach baldige Erholung)',
    t1: 'Wonach',
    t2: 'plant',
    t3: 'ihr',
    t4: 'eure',
    t5: 'baldige',
    t6: 'Erholung',
    t7: '?',
  },
  {
    t0: 'После окончания он ремонтировал неисправные стиральные машины.(Studium defekte Waschmaschinen)',
    t1: 'Nach',
    t2: 'dem',
    t3: 'Studium',
    t4: 'repariert',
    t5: 'er',
    t6: 'defekte',
    t7: 'Waschmaschinen',
    t8: '.',
  },
  {
    t0: 'На выходных она совершила деловую поездку в Берлин.(dienstliche Reise gemacht)',
    t1: 'Am',
    t2: 'Wochenende',
    t3: 'hat',
    t4: 'sie',
    t5: 'eine',
    t6: 'dienstliche',
    t7: 'Reise',
    t8: 'nach',
    t9: 'Berlin',
    t10: 'gemacht',
    t11: '.',
  },
  {
    t0: 'У вас есть номер телефона надежной няни?(ihr Telefonnummer zuverlässigen Babysitters)',
    t1: 'Habt',
    t2: 'ihr',
    t3: 'die',
    t4: 'Telefonnummer',
    t5: 'eines',
    t6: 'zuverlässigen',
    t7: 'Babysitters',
    t8: '?',

  },
  {
    t0: 'Он купил дорогие билеты на самолет.(Flugtickets gekauft)',
    t1: 'Er',
    t2: 'hat',
    t3: 'teure',
    t4: 'Flugtickets',
    t5: 'gekauft',
    t6: '.',

  },
  {
    t0: 'Кто хозяин опасной собаки?(Besitzer gefährlichen)',
    t1: 'Wer',
    t2: 'ist',
    t3: 'der',
    t4: 'Besitzer',
    t5: 'des',
    t6: 'gefährlichen',
    t7: 'Hundes',
    t8: '?',

  },
  {
    t0: 'Он дарит красивую игрушку.(Spielzeug)',
    t1: 'Er',
    t2: 'schenkt',
    t3: 'ein',
    t4: 'schönes',
    t5: 'Spielzeug',
    t6: '.',

  },
  {
    t0: 'Она делает интересную развлекательную программу.(Sie Freizeitprogramm)',
    t1: 'Sie',
    t2: 'macht',
    t3: 'ein',
    t4: 'interessantes',
    t5: 'Freizeitprogramm',
    t6: '.',

  },
  {
    t0: 'Школьница носит модный рюкзак.(Schülerin Rucksack)',
    t1: 'Die',
    t2: 'Schülerin',
    t3: 'trägt',
    t4: 'einen',
    t5: 'modischen',
    t6: 'Rucksack',
    t7: '.',

  },
  {
    t0: 'Они посещают большой блошиный рынок.(Flohmarkt)',
    t1: 'Sie',
    t2: 'besuchen',
    t3: 'einen',
    t4: 'großen',
    t5: 'Flohmarkt',
    t6: '.',

  },
  {
    t0: 'Он поливает большое растение.(Pflanze)',
    t1: 'Er',
    t2: 'gießt',
    t3: 'eine',
    t4: 'große',
    t5: 'Pflanze',
    t6: '.',

  },
  {
    t0: 'Мы приносим чистое белье.(Wäsche)',
    t1: 'Wir',
    t2: 'bringen',
    t3: 'saubere',
    t4: 'Wäsche',
    t5: '.',

  },
  {
    t0: 'Он помогает больной собаке.()',
    t1: 'Er',
    t2: 'hilft',
    t3: 'einem',
    t4: 'kranken',
    t5: 'Hund',
    t6: '.',

  },
  {
    t0: 'Она отвечает новому другу.()',
    t1: 'Sie',
    t2: 'antwortet',
    t3: 'einem',
    t4: 'neuen',
    t5: 'Freund',
    t6: '.',

  },
  {
    t0: 'Они пишут про старый дом.(über)',
    t1: 'Sie',
    t2: 'schreiben',
    t3: 'über',
    t4: 'ein',
    t5: 'altes',
    t6: 'Haus',
    t7: '.',

  },
  {
    t0: 'Он рекомендует знакомой покупательнице.(empfiehlt Käuferin)',
    t1: 'Er',
    t2: 'empfiehlt',
    t3: 'einer',
    t4: 'bekannten',
    t5: 'Käuferin',
    t6: '.',

  },
  {
    t0: 'Она обещает маленькому ребенку.()',
    t1: 'Sie',
    t2: 'verspricht',
    t3: 'einem',
    t4: 'kleinen',
    t5: 'Kind',
    t6: '.',

  },
  {
    t0: 'Это сумка рассеянного пассажира.(zerstreuten Passagier)',
    t1: 'Das',
    t2: 'ist',
    t3: 'eine',
    t4: 'Tasche',
    t5: 'von',
    t6: 'einem',
    t7: 'zerstreuten',
    t8: 'Passagier',
    t9: '.',

  },
  {
    t0: 'Это книга умного школьника.(Schüler)',
    t1: 'Das',
    t2: 'ist',
    t3: 'ein',
    t4: 'Buch',
    t5: 'von',
    t6: 'einem',
    t7: 'klugen',
    t8: 'Schüler',
    t9: '.',

  },
  {
    t0: 'Это компьютер молодой сотрудницы.(Mitarbeiterin)',
    t1: 'Das',
    t2: 'ist',
    t3: 'der',
    t4: 'Computer',
    t5: 'von',
    t6: 'einer',
    t7: 'jungen',
    t8: 'Mitarbeiterin',
    t9: '.',

  },
  {
    t0: 'Это платок старой женщины.(Tuch)',
    t1: 'Das',
    t2: 'ist',
    t3: 'ein',
    t4: 'Tuch',
    t5: 'von',
    t6: 'einer',
    t7: 'alten',
    t8: 'Frau',
    t9: '.',

  },
  {
    t0: 'Это вывеска нового магазина.(Schild Geschäft)',
    t1: 'Das',
    t2: 'ist',
    t3: 'das',
    t4: 'Schild',
    t5: 'von',
    t6: 'einem',
    t7: 'neuen',
    t8: 'Geschäft',
    t9: '.',

  },
  {
    t0: 'Это название популярного кафе.(populären Cafe)',
    t1: 'Das',
    t2: 'ist',
    t3: 'der',
    t4: 'Name',
    t5: 'von',
    t6: 'einem',
    t7: 'populären',
    t8: 'Cafe',
    t9: '.',

  },
  {
    t0: 'Это мои маленькие дети.()',
    t1: 'Das',
    t2: 'sind',
    t3: 'meine',
    t4: 'kleinen',
    t5: 'Kinder',
    t6: '.',

  },
  {
    t0: 'Вы (формально) видите часто его старого дедушку.(Opa)',
    t1: 'Sie',
    t2: 'sehen',
    t3: 'oft',
    t4: 'seinen',
    t5: 'alten',
    t6: 'Opa',
    t7: '.',

  },
  {
    t0: 'Я помогаю моей лучшей подруге.()',
    t1: 'Ich',
    t2: 'helfe',
    t3: 'meiner',
    t4: 'besten',
    t5: 'Freundin',
    t6: '.',

  },
  {
    t0: 'Ты даришь игрушку ее маленькому сыну.(Spielzeug)',
    t1: 'Du',
    t2: 'schenkst',
    t3: 'ihrem',
    t4: 'kleinen',
    t5: 'Sohn',
    t6: 'ein',
    t7: 'Spielzeug',
    t8: '.',

  },
  {
    t0: 'Это ее старый автомобиль.()',
    t1: 'Das',
    t2: 'ist',
    t3: 'ihr',
    t4: 'altes',
    t5: 'Auto',
    t6: '.',

  },
  {
    t0: 'Я посещаю ее новый магазин.(Geschäft)',
    t1: 'Ich',
    t2: 'besuche',
    t3: 'ihr',
    t4: 'neues',
    t5: 'Geschäft',
    t6: '.',

  },
  {
    t0: 'Он ищет его теплую обувь.(Schuhe)',
    t1: 'Er',
    t2: 'sucht',
    t3: 'seine',
    t4: 'warmen',
    t5: 'Schuhe',
    t6: '.',

  },
  {
    t0: 'Она решает свою сложную задачу.(löst Aufgabe)',
    t1: 'Sie',
    t2: 'löst',
    t3: 'ihre',
    t4: 'komplizierte',
    t5: 'Aufgabe',
    t6: '.',

  },
  {
    t0: 'Как выглядит твой старый стол?(Tisch)',
    t1: 'Wie',
    t2: 'sieht',
    t3: 'dein',
    t4: 'alter',
    t5: 'Tisch',
    t6: 'aus',
    t7: '?',

  },
  {
    t0: 'Ее чистая чашка стоит здесь.(Tasse)',
    t1: 'Ihre',
    t2: 'saubere',
    t3: 'Tasse',
    t4: 'steht',
    t5: 'hier',
    t6: '.',

  },
  {
    t0: 'Она следует своим определенным правилам.(folgt Regeln)',
    t1: 'Sie',
    t2: 'folgt',
    t3: 'ihren',
    t4: 'bestimmten',
    t5: 'Regeln',
    t6: '.',

  },
  {
    t0: 'Он помогает моей старой соседке.(Nachbarin)',
    t1: 'Er',
    t2: 'hilft',
    t3: 'meiner',
    t4: 'alten',
    t5: 'Nachbarin',
    t6: '.',

  },
  {
    t0: 'Он берет вещи моей старой бабушки.(Sachen Oma)',
    t1: 'Er',
    t2: 'nimmt',
    t3: 'die',
    t4: 'Sachen',
    t5: 'von',
    t6: 'meiner',
    t7: 'alten',
    t8: 'Oma',
    t9: '.',

  },
  {
    t0: 'Она приносит рюкзак ее маленького брата.(Rucksack)',
    t1: 'Sie',
    t2: 'bringt',
    t3: 'den',
    t4: 'Rucksack',
    t5: 'von',
    t6: 'ihrem',
    t7: 'kleinen',
    t8: 'Bruder',
    t9: '.',

  },
  {
    t0: 'Они видят сумку моей новой соседки.(Nachbarin)',
    t1: 'Sie',
    t2: 'sehen',
    t3: 'die',
    t4: 'Tasche',
    t5: 'von',
    t6: 'meiner',
    t7: 'neuen',
    t8: 'Nachbarin',
    t9: '.',

  },
  {
    t0: 'Она находит мяч своего маленького ребенка.(Ball)',
    t1: 'Sie',
    t2: 'findet',
    t3: 'den',
    t4: 'Ball',
    t5: 'von',
    t6: 'ihrem',
    t7: 'kleinen',
    t8: 'Kind',
    t9: '.',

  },
  {
    t0: 'Новое сообщение слишком длинное.(Nachricht zu)',
    t1: 'Die',
    t2: 'neue',
    t3: 'Nachricht',
    t4: 'ist',
    t5: 'zu',
    t6: 'lang',
    t7: '.',

  },
  {
    t0: 'Высокая девушка сидит здесь.(Mädchen)',
    t1: 'Das',
    t2: 'große',
    t3: 'Mädchen',
    t4: 'sitzt',
    t5: 'hier',
    t6: '.',

  },
  {
    t0: 'У тебя есть замечательная идея.',
    t1: 'Du',
    t2: 'hast',
    t3: 'eine',
    t4: 'wunderbare',
    t5: 'Idee',
    t6: '.',

  },
  {
    t0: 'Он находит это тихое место красивым.(schön)',
    t1: 'Er',
    t2: 'findet',
    t3: 'diesen',
    t4: 'ruhigen',
    t5: 'Ort',
    t6: 'schön',
    t7: '.',

  },
  {
    t0: 'Он ест кислый лимон.(Zitrone)',
    t1: 'Er',
    t2: 'isst',
    t3: 'eine',
    t4: 'saure',
    t5: 'Zitrone',
    t6: '.',

  },
  {
    t0: 'Она ищет правильные ответы.(Antworten)',
    t1: 'Sie',
    t2: 'sucht',
    t3: 'die',
    t4: 'richtigen',
    t5: 'Antworten',
    t6: '.',

  },
  {
    t0: 'Сегодня состоится великолепный концерт.(Konzert)',
    t1: 'Heute',
    t2: 'findet',
    t3: 'ein',
    t4: 'tolles',
    t5: 'Konzert',
    t6: 'statt',
    t7: '.',

  },
  {
    t0: 'Широкие ботинки неудобные.(bequem)',
    t1: 'Die',
    t2: 'weiten',
    t3: 'Schuhe',
    t4: 'sind',
    t5: 'nicht',
    t6: 'bequem',
    t7: '.',

  },
  {
    t0: 'Она хвалит старательного школьника.()',
    t1: 'Sie',
    t2: 'lobt',
    t3: 'den',
    t4: 'fleißigen',
    t5: 'Schüler',
    t6: '.',

  },
  {
    t0: 'Он показывает активным участникам фотографии.(Teilnehmern Fotos)',
    t1: 'Er',
    t2: 'zeigt',
    t3: 'den',
    t4: 'aktiven',
    t5: 'Teilnehmern',
    t6: 'die',
    t7: 'Fotos',
    t8: '.',

  },
  {
    t0: 'Он рассказывает любопытным зрителям забавную историю.(neugierigen Zuschauern Geschichte)',
    t1: 'Er',
    t2: 'erzählt',
    t3: 'den',
    t4: 'neugierigen',
    t5: 'Zuschauern',
    t6: 'eine',
    t7: 'lustige',
    t8: 'Geschichte',
    t9: '.',

  },
  {
    t0: 'Пациент описывает внимательному врачу свою проблему.(Patient beschreibt aufmerksamen Arzt)',
    t1: 'Der',
    t2: 'Patient',
    t3: 'beschreibt',
    t4: 'dem',
    t5: 'aufmerksamen',
    t6: 'Arzt',
    t7: 'sein',
    t8: 'Problem',
    t9: '.',

  },
  {
    t0: 'Старая женщина жалуется мужчине на своих недовольных соседей.(beschwert sauren Nachbarn)',
    t1: 'Die',
    t2: 'alte',
    t3: 'Frau',
    t4: 'beschwert',
    t5: 'sich',
    t6: 'bei',
    t7: 'dem',
    t8: 'Mann',
    t9: 'über',
    t10: 'ihre',
    t11: 'sauren',
    t12: 'Nachbarn',
    t13: '.',

  },
  {
    t0: 'Она дает урок слабому ученику.(Unterricht schwachen Schüler)',
    t1: 'Sie',
    t2: 'gibt',
    t3: 'den',
    t4: 'Unterricht',
    t5: 'einem',
    t6: 'schwachen',
    t7: 'Schüler',
    t8: '.',

  },
  {
    t0: 'Это одежда красивой девушки.(Kleidung hübschen Mädchen)',
    t1: 'Das',
    t2: 'ist',
    t3: 'die',
    t4: 'Kleidung',
    t5: 'von',
    t6: 'einem',
    t7: 'hübschen',
    t8: 'Mädchen',
    t9: '.',

  },
  {
    t0: 'Это документ новой сотрудницы.(Dokument Mitarbeiterin)',
    t1: 'Das',
    t2: 'ist',
    t3: 'das',
    t4: 'Dokument',
    t5: 'von',
    t6: 'der',
    t7: 'neuen',
    t8: 'Mitarbeiterin',
    t9: '.',

  },
  {
    t0: 'Это договоры других коллег.(Verträge Kollegen)',
    t1: 'Das',
    t2: 'sind',
    t3: 'die',
    t4: 'Verträge',
    t5: 'von',
    t6: 'den',
    t7: 'anderen',
    t8: 'Kollegen',
    t9: '.',

  },
  {
    t0: 'Это покупка постоянного покупателя.(Einkauf ständigen Käufer)',
    t1: 'Das',
    t2: 'ist',
    t3: 'der',
    t4: 'Einkauf',
    t5: 'von',
    t6: 'einem',
    t7: 'ständigen',
    t8: 'Käufer',
    t9: '.',

  },

]



const Nominativ = [
  {
    title: 'Maskulinum ',
    text1: 'der rot-e Rock',
    text2: 'ein rot-er Rock',
    text3: 'rot-er Rock',

  },
  {
    title: 'Femininum ',
    text1: 'die gelb-e Bluse',
    text2: 'eine gelb-e Bluse',
    text3: 'gelb-e Bluse',

  },
  {
    title: 'Neutrum',
    text1: 'das grün-e Hemd',
    text2: 'ein grün-es Hemd',
    text3: 'grün-es Hemd',
  },
  {
    title: 'Plural',
    text1: 'die weiß-en Schuche',
    text2: 'weiß-e Schuche',
  },
]
const Akkusativ = [
  {
    title: 'Maskulinum ',
    text1: 'den rot-en Rock',
    text2: 'einen rot-en Rock',
    text3: 'rot-en Rock',

  },
  {
    title: 'Femininum',
    text1: 'die gelb-e Bluse',
    text2: 'eine gelb-e Bluse',
    text3: 'gelb-e Bluse',
  },
  {
    title: 'Neutrum',
    text1: 'das grün-e Hemd',
    text2: 'ein grün-es Hemd',
    text3: 'grün-es Hemd',
  },
  {
    title: 'Plural',
    text1: 'die weiß-en Schuche',
    text2: 'weiß-e Schuche',
  },
]
const Dativ = [
  {
    title: 'Maskulinum ',
    text1: 'dem rot-en Rock',
    text2: 'einem rot-en Rock',
    text3: 'rot-em Rock',

  },
  {
    title: 'Femininum',
    text1: 'der gelb-en Bluse',
    text2: 'einer gelb-en Bluse',
    text3: 'gelb-er Bluse',
  },
  {
    title: 'Neutrum',
    text1: 'dem grün-en Hemd',
    text2: 'einem grün-en Hemd',
    text3: 'grün-em Hemd',
  },
  {
    title: 'Plural',
    text1: 'den weiß-en Schuche-n',
    text2: 'weiß-en Schuche-n',
  },
]
const Genitiv = [
  {
    title: 'Maskulinum ',
    text1: 'des rot-en Rock-s',
    text2: 'eines rot-en Rock-s',
    text3: 'rot-en Rock-s',

  },
  {
    title: 'Femininum',
    text1: 'der gelb-en Bluse',
    text2: 'einer gelb-en Bluse',
    text3: 'gelb-er Bluse',
  },
  {
    title: 'Neutrum',
    text1: 'des grün-en Hemd-s',
    text2: 'eines grün-en Hemd-s',
    text3: 'grün-en Hemd-s',
  },
  {
    title: 'Plural',
    text1: 'den weiß-en Schuche',
    text2: 'weiß-er Schuche',
  },
]


</script>
