<template lang="pug">
.container
  .page-title 
    h2 Interrogativpronomen
  Tabs(:items= 'Interrogativ' title='Interrogativ' )
  .page-block
    .page-title--small 
      h3 Training
    Plaza
    Slot(:SlotData='SlotDataInterrogativ')
</template>


<script setup>
import Tabs from '@/components/Tabs.vue';
import Plaza from '@/components/Plaza.vue';
import Slot from '@/components/Slot.vue'

const Interrogativ = [

  {
    title: 'Nominativ',
    text1: 'Wer',
    text2: 'Was',
    text3: 'Welcher',
    text4: 'Was für ein(er)',
    text5: 'Welche',
    text6: 'Was für eine',
    text7: 'Welches',
    text8: 'Was für ein',
    text9: 'Welche',
    text10: 'Was für Bücher',
    svg3: 'man',
    svg4: 'man',
    svg5: 'frau',
    svg6: 'frau',
    svg7: 'das',
    svg8: 'das',
    svg9: 'group',
    svg10: 'group',

  },
  {
    title: 'Dativ',
    text1: 'Wem',
    text2: 'Welchem',
    text3: 'Was für einem',
    text4: 'Welcher',
    text5: 'Was für einer',
    text6: 'Welchem',
    text7: 'Was für einem',
    text8: 'Welchen',
    text9: 'Was für welchen',
    svg2: 'man',
    svg3: 'man',
    svg4: 'frau',
    svg5: 'frau',
    svg6: 'das',
    svg7: 'das',
    svg8: 'group',
    svg9: 'group',
  },
  {
    title: 'Akkusativ',
    text1: 'Wen',
    text2: 'Was',
    text3: 'Welchen',
    text4: 'Was für einen',
    text5: 'Welche',
    text6: 'Was für eine',
    text7: 'Welches',
    text8: 'Was für ein(e)s',
    text9: 'Welche',
    text10: 'Was für welche',
    svg3: 'man',
    svg4: 'man',
    svg5: 'frau',
    svg6: 'frau',
    svg7: 'das',
    svg8: 'das',
    svg9: 'group',
    svg10: 'group',
  },
  {
    title: 'Genitiv',
    text1: 'Wessen',
    text2: 'Welches',
    text3: 'Was für eines',
    text4: 'Welcher',
    text5: 'Was für einer',
    text6: 'Welches',
    text7: 'Was für eines',
    text8: 'Welcher',
    text9: 'Was für welcher',
    svg2: 'man',
    svg3: 'man',
    svg4: 'frau',
    svg5: 'frau',
    svg6: 'das',
    svg7: 'das',
    svg8: 'group',
    svg9: 'group',
  },
]
const SlotDataInterrogativ = [
  {
    t0: 'Кто это сказал? (gesagt)',
    t1: 'Wer',
    t2: 'hat',
    t3: 'das',
    t4: 'gesagt',
    t5: '?',

  },
  {
    t0: 'Кому вы звонили? (habt angerufen)',
    t1: 'Wen',
    t2: 'habt',
    t3: 'ihr',
    t4: 'angerufen',
    t5: '?',

  },
  {
    t0: 'Что ты ел?()',
    t1: 'Was',
    t2: 'hast',
    t3: 'du',
    t4: 'gegessen',
    t5: '?',

  },
  {
    t0: 'Кому ты дал книгу? (Buch gegeben)',
    t1: 'Wem',
    t2: 'hast',
    t3: 'du',
    t4: 'das',
    t5: 'Buch',
    t6: 'gegeben',
    t7: '?',

  },
  {
    t0: 'Чья это сумка? (Tasche)',
    t1: 'Wessen',
    t2: 'Tasche',
    t3: 'ist',
    t4: 'das',
    t5: '?',

  },
  {
    t0: 'У Мануэлы есть собака. Какая у нее собака?(Manuela)',
    t1: 'Manuela',
    t2: 'hat',
    t3: 'einen',
    t4: 'Hund',
    t5: '.',
    t6: 'Was',
    t7: 'für',
    t8: 'einen',
    t9: 'Hund',
    t10: 'hat',
    t11: 'sie',
    t12: '?',

  },
  {
    t0: 'Какая (собака) принадлежит Мануэле, большая или маленькая?(gehört Manuela große kleine)',
    t1: 'Welcher',
    t2: '(Hund)',
    t3: 'gehört',
    t4: 'Manuela',
    t5: ',',
    t6: 'der',
    t7: 'große',
    t8: 'oder',
    t9: 'der',
    t10: 'kleine',
    t11: '?',

  },
  {
    t0: 'На какой машине ты ездишь? (fährst)',
    t1: 'Was',
    t2: 'für',
    t3: 'ein',
    t4: 'Auto',
    t5: 'fährst',
    t6: 'du',
    t7: '?',
  },
  {
    t0: 'Кто написал письмо? (Brief geschrieben)',
    t1: 'Wer',
    t2: 'hat',
    t3: 'den',
    t4: 'Brief',
    t5: 'geschrieben',
    t6: '?',
  },
  {
    t0: 'Чьи туфли стоят у двери? (Schuhe stehen Tür)',
    t1: 'Wessen',
    t2: 'Schuhe',
    t3: 'stehen',
    t4: 'vor',
    t5: 'der',
    t6: 'Tür',
    t7: '?',

  },
  {
    t0: 'Кому ты хочешь позвонить? (anrufen)',
    t1: 'Wen',
    t2: 'willst',
    t3: 'du',
    t4: 'anrufen',
    t5: '?',

  },
  {
    t0: 'Что вы обычно едите на завтрак? (esst normalerweise Frühstück)',
    t1: 'Was',
    t2: 'esst',
    t3: 'ihr',
    t4: 'normalerweise',
    t5: 'zum',
    t6: 'Frühstück',
    t7: '?',
  },
  {
    t0: 'Кого мы должны поздравить? (gratulieren)',
    t1: 'Wem',
    t2: 'sollen',
    t3: 'wir',
    t4: 'gratulieren',
    t5: '?',
  },
  {
    t0: 'Оливия знакома с официантом. Кого знает Оливия? ()',
    t1: 'Olivia',
    t2: 'kennt',
    t3: 'den',
    t4: 'Kellner',
    t5: '.',
    t6: 'Wen',
    t7: 'kennt',
    t8: 'Olivia',
    t9: '?',
  },
  {
    t0: 'Он закрыл дверь. Что он закрыл? (Tür zugemacht zugemacht)',
    t1: 'Er',
    t2: 'hat',
    t3: 'die',
    t4: 'Tür',
    t5: 'zugemacht',
    t6: '.',
    t7: 'Was',
    t8: 'hat',
    t9: 'er',
    t10: 'zugemacht',
    t11: '?',
  },
  {
    t0: 'Компьютер Кристины сломался. Чей компьютер сломан? (Christinas Computer kaputt)',
    t1: 'Christinas',
    t2: 'Computer',
    t3: 'ist',
    t4: 'kaputt',
    t5: '.',
    t6: 'Wessen',
    t7: 'Computer',
    t8: 'ist',
    t9: 'kaputt',
    t10: '?',
  },
  {
    t0: 'Ученики отвечают учителю. Кому отвечают ученики? (Schüler antworten Lehrer antworten Schüler )',
    t1: 'Die',
    t2: 'Schüler',
    t3: 'antworten',
    t4: 'dem',
    t5: 'Lehrer',
    t6: '.',
    t7: 'Wem',
    t8: 'antworten',
    t9: 'die',
    t10: 'Schüler',
    t11: '?',
  },
  {
    t0: 'Моя двоюродная сестра навещает нас. Кто нас навещает? (Cousine besucht)',
    t1: 'Meine',
    t2: 'Cousine',
    t3: 'besucht',
    t4: 'uns',
    t5: '.',
    t6: 'Wer',
    t7: 'besucht',
    t8: 'uns',
    t9: '?',
  },
  {
    t0: ' Они встретили Йенса. С кем они встретились? (Jens getroffen)',
    t1: 'Sie',
    t2: 'haben',
    t3: 'Jens',
    t4: 'getroffen',
    t5: '.',
    t6: 'Wen',
    t7: 'haben',
    t8: 'sie',
    t9: 'getroffen',
    t10: '?',
  },
  {
    t0: 'Рената выучила стихотворение. Что узнала Рената? (Renate Gedicht gelernt)',
    t1: 'Renate',
    t2: 'hat',
    t3: 'ein',
    t4: 'Gedicht',
    t5: 'gelernt',
    t6: '.',
    t7: 'Was',
    t8: 'hat',
    t9: 'Renate',
    t10: 'gelernt',
    t11: '?',
  },
  {
    t0: 'Мы можем доверять Ульрике. Кому мы можем доверять? (können Ulrike vertrauen)',
    t1: 'Wir',
    t2: 'können',
    t3: 'Ulrike',
    t4: 'vertrauen',
    t5: '.',
    t6: 'Wem',
    t7: 'können',
    t8: 'wir',
    t9: 'vertrauen',
    t10: '?',
  },
  {
    t0: 'Мои друзья уехали в Берлин. Кто ездил в Берлин? (Freunde Berlin gefahren )',
    t1: 'Meine          ?',
    t2: 'Freunde',
    t3: 'sind',
    t4: 'nach',
    t5: 'Berlin',
    t6: 'gefahren',
    t7: '.',
    t8: 'Wer',
    t9: 'ist',
    t10: 'nach',
    t11: 'Berlin',
    t12: 'gefahren',
    t13: '?',
  },
  {
    t0: 'Босс компании водит спортивный автомобиль. На какой машине ездит босс компании? (Firmenboss fährt Sportwagen Wagen )',
    t1: 'Der',
    t2: 'Firmenboss',
    t3: 'fährt',
    t4: 'einen',
    t5: 'Sportwagen',
    t6: '.',
    t7: 'Was',
    t8: 'für',
    t9: 'einen',
    t10: 'Wagen',
    t11: 'fährt',
    t12: 'der',
    t13: 'Firmenboss',
    t14: '?',
  },
  {
    t0: 'Зеленая сумка принадлежит его сестре. Какая сумка принадлежит его сестре? (Schwester gehört grüne Tasche )',
    t1: 'Seiner',
    t2: 'Schwester',
    t3: 'gehört',
    t4: 'die',
    t5: 'grüne',
    t6: 'Tasche',
    t7: '.',
    t8: 'Welche',
    t9: 'Tasche',
    t10: 'gehört',
    t11: 'seiner',
    t12: 'Schwester',
    t13: '?',
  },
  {
    t0: 'Для кого ты покупаешь лимонное мороженое? (Zitroneneis)',
    t1: 'Für',
    t2: 'wen',
    t3: 'kaufst',
    t4: 'du',
    t5: 'Zitroneneis',
    t6: '?',
  },
  {
    t0: 'С кем ты собираешься в отпуск? (fährst Urlaub)',
    t1: 'Mit',
    t2: 'wem',
    t3: 'fährst',
    t4: 'du',
    t5: 'in',
    t6: 'den',
    t7: 'Urlaub',
    t8: '?',
  },
  {
    t0: 'Без чьей помощи ты смог бы решить эту задачу? (Hilfe konntest Aufgabe lösen)',
    t1: 'Ohne',
    t2: 'wessen',
    t3: 'Hilfe',
    t4: 'konntest',
    t5: 'du',
    t6: 'die',
    t7: 'Aufgabe',
    t8: 'lösen',
    t9: '?',
  },
  {
    t0: 'Какое имя вы выбрали для себя? (Namen entschieden)',
    t1: 'Für',
    t2: 'welchen',
    t3: 'Namen',
    t4: 'habt',
    t5: 'ihr',
    t6: 'euch',
    t7: 'entschieden',
    t8: '?',
  },
  {
    t0: 'На какой машине вы поедете к морю? (Auto Meer )',
    t1: 'Mit',
    t2: 'was',
    t3: 'für',
    t4: 'einem',
    t5: 'Auto',
    t6: 'werdet',
    t7: 'ihr',
    t8: 'ans',
    t9: 'Meer',
    t10: 'fahren',
    t11: '?',
  },
  {
    t0: 'На какой автобус ты садишься по утрам? (Bus)',
    t1: 'Welchen     ',
    t2: 'Bus',
    t3: 'nimmst',
    t4: 'du',
    t5: 'morgens',
    t6: '?',

  },
  {
    t0: 'Какое имя тебе больше всего нравится для ребенка? ()',
    t1: 'Welcher',
    t2: 'Name',
    t3: 'gefällt',
    t4: 'dir',
    t5: 'für',
    t6: 'das',
    t7: 'Baby',
    t8: 'am',
    t9: 'besten',
    t10: '?',
  },
  {
    t0: 'С кем бы ты хотел брать уроки танцев? (Tanzunterricht)',
    t1: 'Mit',
    t2: 'wem',
    t3: 'möchtest',
    t4: 'du',
    t5: 'Tanzunterricht',
    t6: 'nehmen',
    t7: '?',

  },
  {
    t0: 'За кого ты меня вообще принимаешь? (Für hältst überhaupt)',
    t1: 'Für',
    t2: 'wen',
    t3: 'hältst',
    t4: 'du',
    t5: 'mich',
    t6: 'überhaupt',
    t7: '?',
  },
  {
    t0: 'Директор школы хотел бы знать, чей велосипед находится на школьном дворе. (Schulleiter möchte Fahrrad Schulhof)',
    t1: 'Der',
    t2: 'Schulleiter',
    t3: 'möchte',
    t4: 'gerne',
    t5: 'wissen',
    t6: ',',
    t7: 'wessen',
    t8: 'Fahrrad',
    t9: 'auf',
    t10: 'dem',
    t11: 'Schulhof',
    t12: 'liegt',
    t13: '.',
  },
  {
    t0: 'Она все еще не уверена, какой второй иностранный язык выбрать. (Fremdsprache wählen)',
    t1: 'Sie',
    t2: 'ist',
    t3: 'sich',
    t4: 'noch',
    t5: 'nicht',
    t6: 'sicher',
    t7: ',',
    t8: 'welche',
    t9: 'zweite',
    t10: 'Fremdsprache',
    t11: 'sie',
    t12: 'wählen',
    t13: 'möchte',
    t14: '.',
  },
  {
    t0: 'Я был шокирован, какой беспорядок! (schockiert Chaos)',
    t1: 'Ich      ',
    t2: 'war',
    t3: 'schockiert',
    t4: ',',
    t5: 'was',
    t6: 'für',
    t7: 'ein',
    t8: 'Chaos',
    t9: '!',
  },
  {
    t0: 'Прежде всего я хочу поблагодарить человека, без помощи которого это было бы невозможно. (Menschen danken Hilfe unmöglich gewesen)',
    t1: 'Ich',
    t2: 'möchte',
    t3: 'vor',
    t4: 'allem',
    t5: 'dem',
    t6: 'Menschen',
    t7: 'danken',
    t8: ',',
    t9: 'ohne',
    t10: 'dessen',
    t11: 'Hilfe',
    t12: 'dies',
    t13: 'unmöglich',
    t14: 'gewesen',
    t15: 'wäre',
    t16: '.',
  },
  {
    t0: 'Она действительно трижды подумала, кому подарить этот подарок на Рождество. (dreimal überlegt Geschenk Weihnachten)',
    t1: 'Sie',
    t2: 'hat',
    t3: 'sich',
    t4: 'wirklich',
    t5: 'dreimal',
    t6: 'überlegt',
    t7: ',',
    t8: 'wem',
    t9: 'sie',
    t10: 'dieses',
    t11: 'Geschenk',
    t12: 'zu',
    t13: 'Weihnachten',
    t14: 'geben',
    t15: 'soll',
    t16: '.',
  },
  {
    t0: 'Без сомнения, детективу с самого начала было ясно, чей это след. (Zweifel Detektiv Anfang Fußabdruck)',
    t1: 'Ohne',
    t2: 'Zweifel',
    t3: 'war',
    t4: 'dem',
    t5: 'Detektiv',
    t6: 'von',
    t7: 'Anfang',
    t8: 'an',
    t9: 'klar',
    t10: ',',
    t11: 'wessen',
    t11: 'Fußabdruck',
    t11: 'das',
    t11: 'war',
    t11: '.',
  },
  {
    t0: 'Мои родители спрашивают меня каждый полдень, какую домашнюю работу я должен выполнить к завтрашнему дню. (Eltern Mittag Hausaufgaben erledigen)',
    t1: 'Meine',
    t2: 'Eltern',
    t3: 'fragen',
    t4: 'mich',
    t5: 'jeden',
    t6: 'Mittag',
    t7: ',',
    t8: 'was',
    t9: 'für',
    t10: 'welche',
    t11: 'Hausaufgaben',
    t11: 'ich',
    t11: 'bis',
    t11: 'morgen',
    t11: 'erledigen',
    t11: 'muss',
    t11: '.',
  },


]





</script>

<style lang="scss" ></style>