<template lang="pug">
.container
  .page-title 
    h2 Konjunktiv II

  .page-block.blue-grey-4
    .page-title--small
      h2 Bildung des Konjunktivs II.
    Tabs(:items= 'Gegenwart' title='Konjunktivs II der Gegenwart (Konjunktiv II von "werden" + Infinitiv)' )
    Tabs(:items= 'Vergangenheit' title='Konjunktiv II der Vergangenheit.(Konjunktivform von sein/ haben + Partizip II)' )
    Tabs(:items= 'FuturI' title='Konjunktiv II Futur I.(Konjunktiv II von "werden" + Infinitiv)' )
    Tabs(:items= 'FuturII' title='Konjunktiv II Futur II.(Konjunktiv II von "werden" + Partizip II + sein)' )
    .page-block.blue-grey-1
      .page-title--small
        h2 Beispiele
      TabsTraining( title='Gegenwart' :SlotData='SlotGegenwart' )
      TabsTraining( title='Vergangenheit' :SlotData='SlotVergangenheit' )
      TabsTraining( title='FuturI' :SlotData='SlotFuturI' )
      TabsTraining( title='FuturII' :SlotData='SlotFuturII' )




  .page-block.blue-grey-4
    .page-title--small
      h2 Bildung des Konjunktivs II mit den Verbformen.
      p Zu den wenigen Verben, die <span>IMMER</span> den Konjunktiv II in der Originalform verwenden, gehören:
    Tabs(:items= 'Verbformen' title='Konjunktivs II mit den Verbformen' )
    .page-block.blue-grey-1
      .page-title--small 
        h2 Beispiele
      TabsTraining( title='Verbformen' :SlotData='SlotVerbformen' )

  .page-block.blue-grey-4
    .page-title--small 
      h2 Bildung des Konjunktivs II mit Modalverben.
    Tabs(:items= 'GegenwartModalverben' title='Konjunktivs II der Gegenwart mit Modalverben ' )
    Tabs(:items= 'VergangenheitModalverben' title='Konjunktiv II der Vergangenheit mit Modalverben.' )
    .page-block.blue-grey-1
      .page-title--small 
        h2 Beispiele
      TabsTraining( title='Modalverben' :SlotData='SlotModalverben' )
      TabsTraining( title='Vergangenheit Modalverben' :SlotData='SlotVergangenheitModalverben' )


 
</template>
<script setup>
import Tabs from '@/components/Tabs.vue';
import TabsTraining from '@/components/TabsTraining.vue';

const Gegenwart = [
  {
    text1: 'ich,er,sie,es würde + Infinitiv',
    text2: 'du würdest + Infinitiv',
    text3: 'ihr würdet + Infinitiv',
    text4: 'wir,sie,Sie würden + Infinitiv',

  },
]
const Vergangenheit = [
  {
    text1: 'ich,er,sie,es wäre/hätte + Partizip II ',
    text2: 'du wärest/hättest + Partizip II',
    text3: 'ihr wäret/hättet + Partizip II',
    text4: 'wir,sie,Sie wären/hätten + Partizip II',
  },
]
const FuturI = [
  {
    text1: 'ich,er,sie,es würde + Infinitiv ',
    text2: 'du würdest + Infinitiv',
    text3: 'ihr ihr würdet + Infinitiv',
    text4: 'wir,sie,Sie würden + Infinitiv',
  },
]
const FuturII = [
  {
    text1: 'ich,er,sie,es würde + Partizip II + sein ',
    text2: 'du würdest + Partizip II + sein ',
    text3: 'ihr ihr würdet + Partizip II + sein ',
    text4: 'wir,sie,Sie würden + Partizip II + sein ',
  },
]
// ´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´
const SlotGegenwart = [
  {
    t0: 'Если бы я только жил во дворце. (doch nur Palast wohnen)',
    t1: 'Würde',
    t2: 'ich',
    t3: 'doch',
    t4: 'nur',
    t5: 'in',
    t6: 'einem',
    t7: 'Palast',
    t8: 'wohnen',
    t9: '.',

  },
  {
    t0: 'Я бы с удовольствием бы поехать в Зальцбург на выходных. (Wochenende so gern Salzburg)',
    t1: 'Ich',
    t2: 'würde',
    t3: 'am',
    t4: 'Wochenende',
    t5: 'so',
    t6: 'gern',
    t7: 'nach',
    t8: 'Salzburg',
    t9: 'fahren',
    t10: '.',

  }, {
    t0: 'Она с удовольствием бы изучать немецкий язык в Австрии. (gern Österreich Deutsch)',
    t1: 'Sie',
    t2: 'würde',
    t3: 'gern',
    t4: 'in',
    t5: 'Österreich',
    t6: 'Deutsch',
    t7: 'lernen',
    t8: '.',

  }, {
    t0: 'Он с удовольствием бы купить машину. (gern Auto)',
    t1: 'Er',
    t2: 'würde',
    t3: 'gern',
    t4: 'ein',
    t5: 'Auto',
    t6: 'kaufen',
    t7: '.',

  }, {
    t0: 'Мы бы навещать тебя каждый год. (jedes Jahr besuchen )',
    t1: 'Wir',
    t2: 'würden',
    t3: 'dich',
    t4: 'jedes',
    t5: 'Jahr',
    t6: 'besuchen',
    t7: '.',

  }, {
    t0: 'Ты бы хотела хотя поплавать завтра на свежем воздухе, но, к сожалению, очень холодно, и это невозможно. (zwar draußen schwimmen leider sehr kalt geht)',
    t1: 'Du',
    t2: 'würdest',
    t3: 'zwar',
    t4: 'gern',
    t5: 'morgen',
    t6: 'draußen',
    t7: 'schwimmen',
    t8: ',',
    t9: 'leider',
    t10: 'ist',
    t11: 'es',
    t12: 'sehr',
    t13: 'kalt',
    t14: 'und',
    t15: 'es',
    t16: 'geht',
    t17: 'nicht',
    t18: '.',
  }, {
    t0: 'Когда бы вы пришли завтра? (ihr morgen)',
    t1: 'Wann',
    t2: 'würdet',
    t3: 'ihr',
    t4: 'morgen',
    t5: 'kommen',
    t6: '?',

  }, {
    t0: 'Если бы я зарабатывал достаточно денег, то купил бы себе новый мобильный телефон. (genug Geld verdienen neues Handy kaufen)',
    t1: 'Wenn',
    t2: 'ich',
    t3: 'genug',
    t4: 'Geld',
    t5: 'verdienen',
    t6: 'würde',
    t7: ',',
    t8: 'dann',
    t9: 'würde',
    t10: 'ich',
    t11: 'mir',
    t12: 'ein',
    t13: 'neues',
    t14: 'Handy',
    t15: 'kaufen',
    t16: '.',
  }, {
    t0: 'Если бы я пекла торт, я бы взяла его с собой на вечеринку. (Kuchen backen Party mitbringen)',
    t1: 'Wenn',
    t2: 'ich',
    t3: 'einen',
    t4: 'Kuchen',
    t5: 'backen',
    t6: 'würde',
    t7: ',',
    t8: 'würde',
    t9: 'ich',
    t10: 'ihn',
    t11: 'zur',
    t12: 'Party',
    t13: 'mitbringen',
    t14: '.',
  }, {
    t0: 'Если бы шел дождь, я бы взял с собой зонтик. (regnen Regenschirm mitnehmen)',
    t1: 'Wenn',
    t2: 'es',
    t3: 'regnen',
    t4: 'würde',
    t5: ',',
    t6: 'würde',
    t7: 'ich',
    t8: 'meinen',
    t9: 'Regenschirm',
    t10: 'mitnehmen',
    t11: '.',

  }, {
    t0: 'Если бы я проголодался, я бы приготовил себе что-нибудь поесть. (hungrig etwas zu essen)',
    t1: 'Wenn',
    t2: 'ich',
    t3: 'hungrig',
    t4: 'wäre',
    t5: ',',
    t6: 'würde',
    t7: 'ich',
    t8: 'mir',
    t9: 'etwas',
    t10: 'zu',
    t11: 'essen',
    t12: 'machen',
    t13: '.',

  }
]
const SlotVergangenheit = [
  {
    t0: 'Вчера мне бы  купилось зеленую машину. (gestern gern grünes Auto)',
    t1: 'Ich',
    t2: 'hätte',
    t3: 'gestern',
    t4: 'gern',
    t5: 'ein',
    t6: 'grünes',
    t7: 'Auto',
    t8: 'gekauft',
    t9: '.',
  },
  {
    t0: 'Мне бы хотелось прийти вчера на курсы немецкого языка. (gern zum Deutschkurs gekommen)',
    t1: 'Ich',
    t2: 'wäre',
    t3: 'gestern',
    t4: 'gern',
    t5: 'zum',
    t6: 'Deutschkurs',
    t7: 'gekommen',
    t8: '.',

  },
  {
    t0: 'Если бы ты вчера остался дома, ты бы больше расслабился. (gestern zu Hause geblieben entspannt)',
    t1: 'Wenn',
    t2: 'du',
    t3: 'gestern',
    t4: 'zu',
    t5: 'Hause',
    t6: 'geblieben',
    t7: 'wärest',
    t8: ',',
    t9: 'hättest',
    t10: 'du',
    t11: 'dich',
    t12: 'mehr',
    t13: 'entspannt',
    t14: '.',

  },
  {
    t0: 'Если бы он чаще выходил на прогулки, он бы чувствовал себя лучше. (öfter spazieren besser gefühlt)',
    t1: 'Wenn',
    t2: 'er',
    t3: 'öfter',
    t4: 'spazieren',
    t5: 'gegangen',
    t6: 'wäre',
    t7: ',',
    t8: 'hätte',
    t9: 'er',
    t10: 'sich',
    t11: 'besser',
    t12: 'gefühlt',
    t13: '.',
  },
  {
    t0: 'Если бы он спланировал свой распорядок дня, у него бы все получилось. (Tagesablauf alles gelungen)',
    t1: 'Wenn',
    t2: 'er',
    t3: 'seinen',
    t4: 'Tagesablauf',
    t5: 'geplant',
    t6: 'hätte',
    t7: ',',
    t8: 'wäre',
    t9: 'es',
    t10: 'ihm',
    t11: 'alles',
    t12: 'gelungen',
    t13: '.',
  },
  {
    t0: 'Если бы она прочитала эту книгу, она бы легко пересказала содержание. (Buch leicht den Inhalt nacherzählt)',
    t1: 'Wenn',
    t2: 'sie',
    t3: 'dieses',
    t4: 'Buch',
    t5: 'gelesen',
    t6: 'hätte',
    t7: ',',
    t8: 'hätte',
    t9: 'sie',
    t10: 'leicht',
    t11: 'den',
    t12: 'Inhalt',
    t13: 'nacherzählt',
    t14: '.',
  },
  {
    t0: 'Если бы она поддержала его мнение, они бы не поссорились. (Meinung unterstützt gestritten)',
    t1: 'Wenn',
    t2: 'sie',
    t3: 'seine',
    t4: 'Meinung',
    t5: 'unterstützt',
    t6: 'hätte',
    t7: ',',
    t8: 'hätten',
    t9: 'sie',
    t10: 'sich',
    t11: 'nicht',
    t12: 'gestritten',
    t13: '.',

  },
  {
    t0: 'Если бы она испекла торт, она бы пригласила гостей. (Kuchen gebacken Gäste eingeladen)',
    t1: 'Wenn',
    t2: 'sie',
    t3: 'den',
    t4: 'Kuchen',
    t5: 'gebacken',
    t6: 'hätte',
    t7: ',',
    t8: 'hätte',
    t9: 'sie',
    t10: 'Gäste',
    t11: 'eingeladen',
    t12: '.',
  },
  {
    t0: 'Если бы она поехала домой, она бы написала нам об этом. (Hause gefahren darüber geschrieben)',
    t1: 'Wenn',
    t2: 'sie',
    t3: 'nach',
    t4: 'Hause',
    t5: 'gefahren',
    t6: 'wäre',
    t7: ',',
    t8: 'hätte',
    t9: 'sie',
    t10: 'uns',
    t11: 'darüber',
    t12: 'geschrieben',
    t13: '.',
  },
  {
    t0: 'Если бы она встретила его вчера, он бы рассказал ей эту историю. ( gestern getroffen Geschichte erzählt)',
    t1: 'Wenn',
    t2: 'sie',
    t3: 'ihn',
    t4: 'gestern',
    t5: 'getroffen',
    t6: 'hätte',
    t7: ',',
    t8: 'hätte',
    t9: 'er',
    t10: 'ihr',
    t11: 'diese',
    t12: 'Geschichte',
    t13: 'erzählt',
    t14: '.',
  },
  {
    t0: 'Если бы ты выучил правила, ты бы лучше написал классную работу. (Regeln besser die Klassenarbeit geschrieben)',
    t1: 'Wenn',
    t2: 'du',
    t3: 'die',
    t4: 'Regeln',
    t5: 'gelernt',
    t6: 'hättest',
    t7: ',',
    t8: 'hättest',
    t9: 'du',
    t10: 'besser',
    t11: 'die',
    t12: 'Klassenarbeit',
    t13: 'geschrieben',
    t14: '.',
  },
  {
    t0: 'Если бы вы использовали этот рецепт, вы бы приготовили вкусный суп на обед. (Rezept verwendet leckere Suppe Mittagessen)',
    t1: 'Wenn',
    t2: 'du',
    t3: 'dieses',
    t4: 'Rezept',
    t5: 'verwendet',
    t6: 'hättest',
    t7: ',',
    t8: 'hättest',
    t9: 'du',
    t10: 'leckere',
    t11: 'Suppe',
    t12: 'zum',
    t13: 'Mittagessen',
    t14: 'gekocht',
    t15: '.',
  },
  {
    t0: 'Если бы я встал раньше, я бы не опоздал на автобус! (früher aufgestanden Bus verpasst)',
    t1: 'Wäre',
    t2: 'ich',
    t3: 'früher',
    t4: 'aufgestanden',
    t5: ',',
    t6: 'hätte',
    t7: 'ich',
    t8: 'den',
    t9: 'Bus',
    t10: 'nicht',
    t11: 'verpasst',
    t12: '!',
  },
  {
    t0: 'Если бы я только больше тренировался, экзамен прошел бы для меня легче. (doch nur mehr geübt Prüfung einfacher verlaufen)',
    t1: 'Hätte',
    t2: 'ich',
    t3: 'doch',
    t4: 'nur',
    t5: 'mehr',
    t6: 'geübt',
    t7: ',',
    t8: 'dann',
    t9: 'wäre',
    t10: 'die',
    t11: 'Prüfung',
    t12: 'für',
    t13: 'mich',
    t14: 'einfacher',
    t15: 'verlaufen',
    t16: '.',
  },
  {
    t0: 'В детстве мне хотелось чаще c удовольствием ездить в отпуск. (Kind öfter Urlaub)',
    t1: 'Ich',
    t2: 'wäre',
    t3: 'als',
    t4: 'Kind',
    t5: 'gerne',
    t6: 'öfter',
    t7: 'in',
    t8: 'den',
    t9: 'Urlaub',
    t10: 'gefahren',
    t11: '.',
  },
  {
    t0: 'Ей бы хотелось приехать, но у нее не было времени. (gerne Zeit)',
    t1: 'Sie',
    t2: 'wäre',
    t3: 'gerne',
    t4: 'gekommen',
    t5: ',',
    t6: 'aber',
    t7: 'sie',
    t8: 'hätte',
    t9: 'keine',
    t10: 'Zeit',
    t11: '.',
  },
  {
    t0: 'Мы бы уже прибыли, если бы ты поторопился. (jetzt schon angekommen mehr beeilt)',
    t1: 'Wir',
    t2: 'wären',
    t3: 'jetzt',
    t4: 'schon',
    t5: 'angekommen',
    t6: ',',
    t7: 'wenn',
    t8: 'du',
    t9: 'dich',
    t10: 'mehr',
    t11: 'beeilt',
    t12: 'hättest',
    t13: '.',
  },
  {
    t0: 'Я бы пошел в парк, если бы не шел дождь. (Park gegangen geregnet)',
    t1: 'Ich',
    t2: 'wäre',
    t3: 'in',
    t4: 'den',
    t5: 'Park',
    t6: 'gegangen',
    t7: ',',
    t8: 'wenn',
    t9: 'es',
    t10: 'nicht',
    t11: 'geregnet',
    t12: 'hätte',
    t13: '.',

  },
  {
    t0: 'Я бы пробежал марафон, если бы подготовился. (Marathon gelaufen vorbereitet)',
    t1: 'Ich',
    t2: 'wäre',
    t3: 'den',
    t4: 'Marathon',
    t5: 'gelaufen',
    t6: ',',
    t7: 'wenn',
    t8: 'ich',
    t9: 'mich',
    t10: 'vorbereitet',
    t11: 'hätte',
    t12: '.',
  },
  {
    t0: 'Я бы прыгнул с 10-метровой вышки, если бы меньше страха имел. (10-Meter-Turm gesprungen weniger Angst)',
    t1: 'Ich',
    t2: 'wäre',
    t3: 'vom',
    t4: '10-Meter-Turm',
    t5: 'gesprungen',
    t6: ',',
    t7: 'wenn',
    t8: 'ich',
    t9: 'weniger',
    t10: 'Angst',
    t11: 'gehabt',
    t12: 'hätte',
    t13: '.',
  },
]
const SlotFuturI = [
  {
    t0: 'Если бы сумка была больше, в нее поместилось бы больше бутылок. (Tasche größer Flaschen hineinpassen)',
    t1: 'Wenn',
    t2: 'die',
    t3: 'Tasche',
    t4: 'größer',
    t5: 'wäre',
    t6: ',',
    t7: 'würden',
    t8: 'mehr',
    t9: 'Flaschen',
    t10: 'hineinpassen',
    t11: '.',

  },
]
const SlotFuturII = [
  {
    t0: 'Если бы я был дома, я был бы лучше защищен. (Hause besser gewahrt)',
    t1: 'Wenn',
    t2: 'ich',
    t3: 'zu',
    t4: 'Hause',
    t5: 'wäre',
    t6: ',',
    t7: 'würde',
    t8: 'ich',
    t9: 'besser',
    t10: 'gewahrt',
    t11: 'sein',
    t12: '.',
  },
]


// =============================================================
// =============================================================
// =============================================================
// =============================================================

const Verbformen = [
  {
    title: 'sein',
    text1: 'ich,er,sie,es wäre ',
    text2: 'du wärest',
    text3: 'ihr wäret',
    text4: 'wir,sie,Sie wären ',
  },
  {
    title: 'haben',
    text1: 'ich,er,sie,es hätte',
    text2: 'du hättest',
    text3: 'ihr hättet',
    text4: 'wir,sie,Sie hätten',
  },
  {
    title: 'werden',
    text1: 'ich,er,sie,es würde',
    text2: 'du würdest',
    text3: 'ihr würdet',
    text4: 'wir,sie,Sie würden',
  },
  {
    title: 'finden',
    text1: 'ich,er,sie,es fände',
    text2: 'du fändest',
    text3: 'ihr fändet',
    text4: 'wir,sie,Sie fänden',
  },
  {
    title: 'gehen',
    text1: 'ich,er,sie,es ginge',
    text2: 'du gingest',
    text3: 'ihr ginget',
    text4: 'wir,sie,Sie gingen',
  },
  {
    title: 'kommen',
    text1: 'ich,er,sie,es käme',
    text2: 'du kämest',
    text3: 'ihr kämet',
    text4: 'wir,sie,Sie kämen',
  },
  {
    title: 'lassen',
    text1: 'ich,er,sie,es ließe',
    text2: 'du ließest',
    text3: 'ihr ließet',
    text4: 'wir,sie,Sie ließen',
  },
  {
    title: 'schlafen',
    text1: 'ich,er,sie,es schliefe',
    text2: 'du schliefest',
    text3: 'ihr schliefet',
    text4: 'wir,sie,Sie schliefen',
  },
  {
    title: 'wissen',
    text1: 'ich,er,sie,es wüsste',
    text2: 'du wüsstest',
    text3: 'ihr wüsstet',
    text4: 'wir,sie,Sie wüssten',
  },
]
const SlotVerbformen = [
  {
    t0: 'Я хотел бы узнать больше об искусстве. (gern über Kunst)',
    t1: 'Ich',
    t2: 'wüsste',
    t3: 'gern',
    t4: 'mehr',
    t5: 'über',
    t6: 'Kunst',
    t7: '.',

  },
  {
    t0: 'На самом деле автобус должен был прийти в 10 утра. (Eigentlich käme )',
    t1: 'Eigentlich',
    t2: 'käme',
    t3: 'der',
    t4: 'Bus',
    t5: 'um',
    t6: '10',
    t7: 'Uhr',
    t8: '.',

  },
  {
    t0: 'Мне также подойдет встреча в среду. (Für ginge auch Termin am Mittwoch)',
    t1: 'Für',
    t2: 'mich',
    t3: 'ginge',
    t4: 'auch',
    t5: 'ein',
    t6: 'Termin',
    t7: 'am',
    t8: 'Mittwoch',
    t9: '.',

  },
  {
    t0: 'Если  ты пишешь аккуратнее, то я бы лучше прочитал твой текст. (ordentlicher schriebest läse Text besser)',
    t1: 'Wenn',
    t2: 'du',
    t3: 'ordentlicher',
    t4: 'schriebest',
    t5: ',',
    t6: 'dann',
    t7: 'läse',
    t8: 'ich',
    t9: 'deinen',
    t10: 'Text',
    t11: 'besser',
    t12: '.',
  },
]
// =============================================================
// =============================================================
// =============================================================
// =============================================================

const GegenwartModalverben = [
  {
    title: 'dürfen',
    text1: 'ich,er,sie,es dürfte + Infinitiv  ',
    text2: 'du dürftest + Infinitiv',
    text3: 'ihr dürftet + Infinitiv',
    text4: 'wir,sie,Sie dürften  + Infinitiv',
  },
  {
    title: 'können',
    text1: 'ich,er,sie,es könnte + Infinitiv  ',
    text2: 'du könntest + Infinitiv',
    text3: 'ihr könntet + Infinitiv',
    text4: 'wir,sie,Sie könnten  + Infinitiv',
  },
  {
    title: 'mögen',
    text1: 'ich,er,sie,es möchte + Infinitiv  ',
    text2: 'du möchtest + Infinitiv',
    text3: 'ihr möchtet + Infinitivn',
    text4: 'wir,sie,Sie möchten  + Infinitiv',
  },
  {
    title: 'müssen',
    text1: 'ich,er,sie,es müsste + Infinitiv  ',
    text2: 'du müsstest + Infinitiv',
    text3: 'ihr müsstet + Infinitiv',
    text4: 'wir,sie,Sie müssten  + Infinitiv',
  },
  {
    title: 'sollen',
    text1: 'ich,er,sie,es sollte + Infinitiv  ',
    text2: 'du solltest + Infinitiv',
    text3: 'ihr solltet + Infinitiv',
    text4: 'wir,sie,Sie sollten  + Infinitiv',
  },
  {
    title: 'wollen',
    text1: 'ich,er,sie,es wollte + Infinitiv  ',
    text2: 'du wolltest + Infinitiv',
    text3: 'ihr wolltet + Infinitiv',
    text4: 'wir,sie,Sie wollten  + Infinitiv',
  },
]
const VergangenheitModalverben = [
  {
    title: 'dürfen',
    text1: 'ich,er,sie,es hätte + Infinitiv + dürfen',
    text2: 'du hättest + Infinitiv + dürfen',
    text3: 'ihr hättet + Infinitiv + dürfen',
    text4: 'wir,sie,Sie hätten + Infinitiv + dürfen',
  },
  {
    title: 'können',
    text1: 'ich,er,sie,es hätte + Infinitiv + können',
    text2: 'du hättest + Infinitiv + können',
    text3: 'ihr hättet + Infinitiv + können',
    text4: 'wir,sie,Sie hätten + Infinitiv + können',
  },

  {
    title: 'mögen',
    text1: 'ich,er,sie,es hätte + Infinitiv + mögen',
    text2: 'du hättest + Infinitiv + mögen',
    text3: 'ihr hättet + Infinitiv + mögen',
    text4: 'wir,sie,Sie hätten + Infinitiv + mögen',
  },
  {
    title: 'müssen',
    text1: 'ich,er,sie,es hätte + Infinitiv + müssen',
    text2: 'du hättest + Infinitiv + müssen',
    text3: 'ihr hättet + Infinitiv + müssen',
    text4: 'wir,sie,Sie hätten + Infinitiv + müssen',
  },

  {
    title: 'sollen',
    text1: 'ich,er,sie,es hätte + Infinitiv + sollen',
    text2: 'du hättest + Infinitiv + sollen',
    text3: 'ihr hättet + Infinitiv + sollen',
    text4: 'wir,sie,Sie hätten + Infinitiv + sollen',
  },
  {
    title: 'wollen',
    text1: 'ich,er,sie,es hätte + Infinitiv + wollen',
    text2: 'du hättest + Infinitiv + wollen',
    text3: 'ihr hättet + Infinitiv + wollen',
    text4: 'wir,sie,Sie hätten + Infinitiv + wollen',
  },

]
// ´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´
const SlotModalverben = [
  {
    t0: 'Затем я спросил, можно ли мне позвонить, и позвонил в Скотланд-Ярд. (fragte ob telefonieren rief Scotland Yard an)',
    t1: 'Dann',
    t2: 'fragte',
    t3: 'ich',
    t4: ',',
    t5: 'ob',
    t6: 'ich',
    t7: 'telefonieren',
    t8: 'dürfte',
    t9: 'und',
    t10: 'rief',
    t11: 'Scotland',
    t12: 'Yard',
    t13: 'an',
    t14: '.',

  },
  {
    t0: 'Если я позволю  вкратце объяснить? (erklären)',
    t1: 'Wenn',
    t2: 'ich',
    t3: 'kurz',
    t4: 'erklären',
    t5: 'dürfte',
    t6: '?',

  },
  {
    t0: 'Я думаю, это позволено быть так. ',
    t1: 'Ich',
    t2: 'denke',
    t3: ',',
    t4: 'das',
    t5: 'dürfte',
    t6: 'so',
    t7: 'sein',
    t8: '.',

  },
  {
    t0: 'Вы позволяете бы иметь много общего. (vieles gemeinsam)',
    t1: 'Ihr',
    t2: 'dürftet',
    t3: 'vieles',
    t4: 'gemeinsam',
    t5: 'haben',
    t6: '.',

  },
  {
    t0: 'Вы полагаете, вы бы позволяете обмануть. (ihr glaubt betrügen)',
    t1: 'Ihr',
    t2: 'glaubt',
    t3: ',',
    t4: 'ihr',
    t5: 'dürftet',
    t6: 'betrügen',
    t7: '.',

  },
  {
    t0: 'Я сказал, вы бы позволять прийти сюда. (sagte hier herkommen)',
    t1: 'Ich',
    t2: 'sagte',
    t3: ',',
    t4: 'ihr',
    t5: 'dürftet',
    t6: 'hier',
    t7: 'herkommen',
    t8: '.',

  },
  {
    t0: 'Вы бы можете помочь нам.',
    t1: 'Ihr',
    t2: 'könntet',
    t3: 'uns',
    t4: 'helfen',
    t5: '.',

  },
  {
    t0: 'Вы могли бы сделать что-то подобное. (so etwas machen)',
    t1: 'Ihr',
    t2: 'könntet',
    t3: 'so',
    t4: 'etwas',
    t5: 'machen',
    t6: '.',

  },
  {
    t0: 'Вы могли бы стать подругами. (Ihr Freundinnen)',
    t1: 'Ihr',
    t2: 'könntet',
    t3: 'Freundinnen',
    t4: 'werden',
    t5: '.',

  },
  {
    t0: 'Вероятно, она думает, что это мог быть человек. (meint wohl menschlich)',
    t1: 'Sie',
    t2: 'meint',
    t3: 'wohl',
    t4: ',',
    t5: 'es',
    t6: 'könnte',
    t7: 'menschlich',
    t8: 'sein',
    t9: '.',

  },
  {
    t0: 'Но, это мог быть и кто-то ещё. (auch jemand anderes)',
    t1: 'Aber',
    t2: 'es',
    t3: 'könnte',
    t4: 'auch',
    t5: 'jemand',
    t6: 'anderes',
    t7: 'sein',
    t8: '.',

  },

  {
    t0: 'Работайте над чем бы хотите. (an auch immer ihr)',
    t1: 'Arbeitet',
    t2: 'an',
    t3: 'was',
    t4: 'auch',
    t5: 'immer',
    t6: 'ihr',
    t7: 'möchtet',
    t8: '.',

  },
  {
    t0: 'Мы имеем пару сосисек, если вы бы хотеть. (Wir ein Paar Würstchen ihr)',
    t1: 'Wir',
    t2: 'haben',
    t3: 'ein',
    t4: 'paar',
    t5: 'Würstchen',
    t6: ',',
    t7: 'wenn',
    t8: 'ihr',
    t9: 'möchtet',
    t10: '.',

  },
  {
    t0: 'Совсем неплохо, но ты бы должен достичь, что я им верить. (Gar übel, erreichen Ihnen glaube)',
    t1: 'Gar',
    t2: 'nicht',
    t3: 'übel',
    t4: ',',
    t5: 'aber',
    t6: 'Sie',
    t7: 'müssten',
    t8: 'erreichen',
    t9: ',',
    t10: 'dass',
    t11: 'ich',
    t12: 'Ihnen',
    t13: 'glaube',
    t14: '.',

  },

  {
    t0: 'Им бы должно тебя в тележку посадить. (dich Karre legen)',
    t1: 'Sie',
    t2: 'müssten',
    t3: 'dich',
    t4: 'in',
    t5: 'eine',
    t6: 'Karre',
    t7: 'legen',
    t8: '.',

  },
  {
    t0: 'Они бы должны время от времени на Марс приезжать. (Sie gelegentlich auf Mars)',
    t1: 'Sie',
    t2: 'müssten',
    t3: 'gelegentlich',
    t4: 'auf',
    t5: 'den',
    t6: 'Mars',
    t7: 'kommen',
    t8: '.',

  },
  {
    t0: 'Я думаю,  это должно вот так произойти . (passieren)',
    t1: 'Ich',
    t2: 'denke',
    t3: ',',
    t4: 'es',
    t5: 'sollte',
    t6: 'so',
    t7: 'passieren',
    t8: '.',

  },
  {
    t0: 'Ничего не произошло  как должно было. (Nichts passiert wie es)',
    t1: 'Nichts',
    t2: 'ist',
    t3: 'passiert',
    t4: 'wie',
    t5: 'es',
    t6: 'sollte',
    t7: '.',

  },
  {
    t0: 'Я делал всё, что вы бы хотели. (tat alles ihr)',
    t1: 'Ich',
    t2: 'tat',
    t3: 'alles',
    t4: ',',
    t5: 'was',
    t6: 'ihr',
    t7: 'wolltet',
    t8: '.',

  },

  {
    t0: 'Я думал, вы бы хотели настоящего ребенка. (dachte echtes Kind)',
    t1: 'Ich',
    t2: 'dachte',
    t3: ',',
    t4: 'ihr',
    t5: 'wolltet',
    t6: 'ein',
    t7: 'echtes',
    t8: 'Kind',
    t9: '.',

  },

  {
    t0: 'Они хотели бы посмотреть, что я буду с этим делать. (damit mache)',
    t1: 'Sie',
    t2: 'wollten',
    t3: 'sehen',
    t4: ',',
    t5: 'was',
    t6: 'ich',
    t7: 'damit',
    t8: 'mache',
    t9: '.',
  },

]
const SlotVergangenheitModalverben = [
  {
    t0: 'Ему бы не следовало так врываться позволять. (nicht so reinplatzen)',
    t1: 'Er',
    t2: 'hätte',
    t3: 'nicht',
    t4: 'so',
    t5: 'reinplatzen',
    t6: 'dürfen',
    t7: '.',

  },
  {
    t0: 'Ему бы никогда одному идти  позволять. (nie alleine )',
    t1: 'Er',
    t2: 'hätte',
    t3: 'nie',
    t4: 'alleine',
    t5: 'gehen',
    t6: 'dürfen',
    t7: '.',

  },
  {
    t0: 'Ему бы ее не провоцировать позволять. (nicht provozieren)',
    t1: 'Er',
    t2: 'hätte',
    t3: 'sie',
    t4: 'nicht',
    t5: 'provozieren',
    t6: 'dürfen',
    t7: '.',

  },
  {
    t0: 'Вам бы из дома никогда  оставлять позволять . (Haus nie verlassen)',
    t1: 'Ihr',
    t2: 'hättet',
    t3: 'das',
    t4: 'Haus',
    t5: 'nie',
    t6: 'verlassen',
    t7: 'dürfen',
    t8: '.',

  },
  {
    t0: 'Вы  бы не сюда приходить позволять. (nicht herkommen)',
    t1: 'Ihr',
    t2: 'hättet',
    t3: 'nicht',
    t4: 'herkommen',
    t5: 'dürfen',
    t6: '.',
  },
  {
    t0: 'Но ты мог бы уйти.(gehen)',
    t1: 'Aber',
    t2: 'du',
    t3: 'hättest',
    t4: 'gehen',
    t5: 'können',
    t6: '.',

  },
  {
    t0: 'Или ты с ним  бы пойти мог. (Oder ihm gehen)',
    t1: 'Oder',
    t2: 'du',
    t3: 'hättest',
    t4: 'mit',
    t5: 'ihm',
    t6: 'gehen',
    t7: 'können',
    t8: '.',

  },
  {
    t0: ' Человек, там я бы к этому побывать хотеть. (Mann,  dabei sein)',
    t1: 'Mann',
    t2: ',',
    t3: 'da',
    t4: 'hätte',
    t5: 'ich',
    t6: 'dabei',
    t7: 'sein',
    t8: 'mögen',
    t9: '.',

  },
  {
    t0: 'Все бы также неправильно идти могло. (schief gehen)',
    t1: 'Es',
    t2: 'hätte',
    t3: 'auch',
    t4: 'schief',
    t5: 'gehen',
    t6: 'können',
    t7: '.',

  },
  {
    t0: 'Это бы давно здесь быть должно. (längst hier sein)',
    t1: 'Es',
    t2: 'hätte',
    t3: 'längst',
    t4: 'hier',
    t5: 'sein',
    t6: 'sollen',
    t7: '.',

  },
  {
    t0: 'Это бы не так закончиться должно. (nicht enden)',
    t1: 'Es',
    t2: 'hätte',
    t3: 'nicht',
    t4: 'so',
    t5: 'enden',
    t6: 'müssen',
    t7: '.',
  },
  {
    t0: 'Как будто ты в тюрьму хотел. (Als ins Gefängnis)',
    t1: 'Als',
    t2: 'hättest',
    t3: 'du',
    t4: 'ins',
    t5: 'Gefängnis',
    t6: 'wollen',
    t7: '.',

  },
  {
    t0: 'Делай все так, как бы ты их делать хотел. (Mach Dinge so machen)',
    t1: 'Mach',
    t2: 'die',
    t3: 'Dinge',
    t4: 'so',
    t5: ',',
    t6: 'wie',
    t7: 'du',
    t8: 'sie',
    t9: 'hättest',
    t10: 'machen',
    t11: 'wollen',
    t12: '.',
  },
  {
    t0: 'Если бы мне разрешили работать в ресторане, я бы заработал денег. (im Restaurant arbeiten Geld verdienen)',
    t1: 'Wenn',
    t2: 'ich',
    t3: 'im',
    t4: 'Restaurant',
    t5: 'hätte',
    t6: 'arbeiten',
    t7: 'dürfen',
    t8: ',',
    t9: 'würde',
    t10: 'ich',
    t11: 'Geld',
    t12: 'verdienen',
    t13: '.',
  },
  {
    t0: 'Если бы я умел плавать, я бы пошел в открытый бассейн. (schwimmen ins Freibad)',
    t1: 'Wenn',
    t2: 'ich',
    t3: 'hätte',
    t4: 'schwimmen',
    t5: 'können',
    t6: ',',
    t7: 'wäre',
    t8: 'ich',
    t9: 'ins',
    t10: 'Freibad',
    t11: 'gegangen',
    t12: '.',
  },
  {
    t0: 'Мы надеемся, что мы  не должны объяснять, где именно водитель травмироваться бы мог , если бы бревно просто немного дальше в машину скользнуло бы. (Wir,,der Fahrer verletzen,der Baumstamm weiter in das Auto gerutscht)',
    t1: 'Wir',
    t2: 'hoffen',
    t3: ',',
    t4: 'dass',
    t5: 'wir',
    t6: 'nicht',
    t7: 'erklären',
    t8: 'müssen',
    t9: ',',
    t10: 'wo',
    t11: 'genau',
    t12: 'sich',
    t13: 'der',
    t14: 'Fahrer',
    t15: 'hätte',
    t16: 'verletzen',
    t17: 'können',
    t18: ',',
    t19: 'wenn',
    t20: 'der',
    t21: 'Baumstamm',
    t22: 'nur',
    t23: 'ein',
    t24: 'bisschen',
    t25: 'weiter',
    t26: 'in',
    t27: 'das',
    t28: 'Auto',
    t29: 'gerutscht',
    t30: 'wäre',
    t31: '.',
  },


]



</script>

<style lang="scss"></style>