<template lang="pug">
.container
  .page-title 
    h2 Nomen-Verb-Verbindungen

  .page-block
    .page-title--small 
      h2 Training
    TabsTraining( title='' :SlotData='SlotDativ' )


 
    
 
</template>
<script setup>
import Tabs from '@/components/Tabs.vue';
import TabsTraining from '@/components/TabsTraining.vue';
import Plaza from '@/components/Plaza.vue';
import Slot from '@/components/Slot.vue'

const SlotDativ = [
  {
    t0: 'Перед сложными контрактами следует остерегаться. (Vor Verträgen sollte man sich )',
    t1: 'Vor',
    t2: 'komplizierten',
    t3: 'Verträgen',
    t4: 'sollte',
    t5: 'man',
    t6: 'sich',
    t7: 'in',
    t8: 'Acht',
    t9: 'nehmen',
    t10: '.',

  }, {
    t0: 'Важно также проявлять уважение к конкурентам.(Konkurrenz )',
    t1: 'Es',
    t2: 'ist',
    t3: 'wichtig',
    t4: ',',
    t5: 'auch',
    t6: 'der',
    t7: 'Konkurrenz',
    t8: 'Achtung',
    t9: 'entgegenzubringen',
    t10: '.',

  }, {
    t0: 'У меня есть намерение сделать карьеру. (Absicht Karriere)',
    t1: 'Ich',
    t2: 'habe',
    t3: 'die',
    t4: 'Absicht',
    t5: ',',
    t6: 'Karriere',
    t7: 'zu',
    t8: 'machen',
    t9: '.',

  }, {
    t0: 'Все сотрудники могут в любое время изменить свой пароль. (Mitarbeitenden Passwort jederzeit)',
    t1: 'Аlle',
    t2: 'Mitarbeitenden',
    t3: 'können',
    t4: 'an',
    t5: 'ihrem',
    t6: 'Passwort',
    t7: 'jederzeit',
    t8: 'eine',
    t9: 'Änderung',
    t10: 'vornehmen',
    t11: '.',
  }, {
    t0: 'Достижения группы находят признание во всем мире. (Leistungen Konzerns weltweit Anerkennung)',
    t1: 'Die',
    t2: 'Leistungen',
    t3: 'des',
    t4: 'Konzerns',
    t5: 'finden',
    t6: 'weltweit',
    t7: 'Anerkennung',
    t8: '.',

  }, {
    t0: 'Марина отвечает всем требованиям, указанным в объявлении о вакансии. (Anforderungen Stellenausschreibung)',
    t1: 'Marina',
    t2: 'erfüllt',
    t3: 'alle',
    t4: 'Anforderungen',
    t5: 'in',
    t6: 'der',
    t7: 'Stellenausschreibung',
    t8: '.',
  }, {
    t0: 'Мы уже отправили запрос в ремесленную мастерскую на ремонтные работы. (Renovierungsarbeiten bereits Anfrage Handwerksbetrieb)',
    t1: 'Für',
    t2: 'die',
    t3: 'Renovierungsarbeiten',
    t4: 'haben',
    t5: 'wir',
    t6: 'bereits',
    t7: 'eine',
    t8: 'Anfrage',
    t9: 'an',
    t10: 'einen',
    t11: 'Handwerksbetrieb',
    t12: 'gestellt',
    t13: '.',

  }, {
    t0: 'Компания сделала мне отличное предложение. (Firma Angebot )',
    t1: 'Die',
    t2: 'Firma',
    t3: 'hat',
    t4: 'mir',
    t5: 'ein',
    t6: 'tolles',
    t7: 'Angebot',
    t8: 'gemacht',
    t9: '.',

  }, {
    t0: 'Я займусь заказом клиента прямо сейчас. (Bestellung Kunden Angriff)',
    t1: 'Ich',
    t2: 'werde',
    t3: 'die',
    t4: 'Bestellung',
    t5: 'des',
    t6: 'Kunden',
    t7: 'gleich',
    t8: 'in',
    t9: 'Angriff',
    t10: 'nehmen',
    t11: '.',

  }, {
    t0: 'Мысль о моем первом дне на работе пугает меня. (Gedanke Arbeitstag Angst)',
    t1: 'Der',
    t2: 'Gedanke',
    t3: 'an',
    t4: 'meinen',
    t5: 'ersten',
    t6: 'Arbeitstag',
    t7: 'macht',
    t8: 'mir',
    t9: 'Angst',
    t10: '.',

  }, {
    t0: 'Я очень обеспокоен тем, что этот вопрос будет решен быстро. (großes Anliegen Sache wird)',
    t1: 'Es',
    t2: 'ist',
    t3: 'mir',
    t4: 'ein',
    t5: 'großes',
    t6: 'Anliegen',
    t7: ',',
    t8: 'dass',
    t9: 'die',
    t10: 'Sache',
    t11: 'schnell',
    t12: 'geklärt',
    t13: 'wird',
    t14: '.',

  }, {
    t0: 'Вы имеете право на отпуск продолжительностью не менее 20 дней в году. (Anspruch Tage Urlaub)',
    t1: 'Sie',
    t2: 'haben',
    t3: 'Anspruch',
    t4: 'auf',
    t5: 'mindestens',
    t6: '20',
    t7: 'Tage',
    t8: 'Urlaub',
    t9: 'pro',
    t10: 'Jahr',
    t11: '.',

  }, {
    t0: 'Мы должны использовать возможности финансирования через городской совет. (Fördermöglichkeiten Stadt Anspruch)',
    t1: 'Wir',
    t2: 'sollten',
    t3: 'Fördermöglichkeiten',
    t4: 'durch',
    t5: 'den',
    t6: 'Stadt',
    t7: 'strärke',
    t8: 'in',
    t9: 'Anspruch',
    t10: 'nehmen',
    t11: '.',

  }, {
    t0: 'Мартина Морена подала заявку на учредительный грант. (Antrag Gründungszuschuss)',
    t1: 'Martina',
    t2: 'Morena',
    t3: 'hat',
    t4: 'einen',
    t5: 'Antrag',
    t6: 'auf',
    t7: 'Gründungszuschuss',
    t8: 'gestellt',
    t9: '.',

  }, {
    t0: 'Результаты совещаний часто не используются. (Ergebnisse Besprechungen zur Anwendung)',
    t1: 'Die',
    t2: 'Ergebnisse',
    t3: 'aus',
    t4: 'Besprechungen',
    t5: 'kommen',
    t6: 'oft',
    t7: 'nicht',
    t8: 'zur',
    t9: 'Anwendung',
    t10: '.',
  }, {
    t0: 'Список адресов ждет меня. Я должен вернуться к работе. (Adressenliste Arbeit)',
    t1: 'Die',
    t2: 'Adressenliste',
    t3: 'wartet',
    t4: 'auf',
    t5: 'mich',
    t6: '.',
    t7: 'Ich',
    t8: 'muss',
    t9: 'wieder',
    t10: 'an',
    t11: 'die',
    t12: 'Arbeit',
    t13: 'gehen',
    t14: '.',
  }, {
    t0: 'Мы приобрели нового крупного клиента. Вы проделали очень хорошую работу. (großen Kunden Arbeit)',
    t1: 'Wir',
    t2: 'haben',
    t3: 'einen',
    t4: 'neuen',
    t5: 'großen',
    t6: 'Kunden',
    t7: 'gewonnen',
    t8: '.',
    t9: 'Ihr',
    t10: 'habt',
    t11: 'sehr',
    t12: 'gute',
    t13: 'Arbeit',
    t14: 'geleistet',
    t15: '.',
  }, {
    t0: 'Хранение данных о наших клиентах требует много работы. (Pflege Kundendaten Arbeit)',
    t1: 'Die',
    t2: 'Pflege',
    t3: 'unserer',
    t4: 'Kundendaten',
    t5: 'macht',
    t6: 'viel',
    t7: 'Arbeit',
    t8: '.',
  }, {
    t0: 'Пошли, перерыв окончен ! Давайте вернемся к работе. (Komm Pause Arbeit)',
    t1: 'Komm',
    t2: ',',
    t3: 'die',
    t4: 'Pause',
    t5: 'ist',
    t6: 'vorbei',
    t7: '!',
    t8: 'Machen',
    t9: 'wir',
    t10: 'uns',
    t11: 'wieder',
    t12: 'an',
    t13: 'die',
    t14: 'Arbeit',
    t15: '.',

  }, {
    t0: 'Где находится предложение для компании kraxel? (Angebot Firma)',
    t1: 'Wo',
    t2: 'ist',
    t3: 'das',
    t4: 'Angebot',
    t5: 'für',
    t6: 'die',
    t7: 'Firma',
    t8: 'kraxel',
    t9: '.',

  }, {
    t0: 'Я пришел к выводу, что мы должны работать над компенсацией клиентам. (Auffassung Kunden Entschädigung)',
    t1: 'Ich',
    t2: 'bin',
    t3: 'zu',
    t4: 'der',
    t5: 'Auffassung',
    t6: 'gelernt',
    t7: ',',
    t8: 'dass',
    t9: 'wir',
    t10: 'der',
    t11: 'Kunden',
    t12: 'eine',
    t13: 'Entschädigung',
    t14: 'arbeiten',
    t15: 'sollten',
    t16: '.',
  }, {
    t0: 'С помощью небольшого анекдота вы легко завоюете внимание своих слушателей. (Anekdote Aufmerksamkeit Zuhörer)',
    t1: 'Mit',
    t2: 'einer',
    t3: 'kleinen',
    t4: 'Anekdote',
    t5: 'gewinnen',
    t6: 'sie',
    t7: 'leicht',
    t8: 'die',
    t9: 'Aufmerksamkeit',
    t10: 'ihrer',
    t11: 'Zuhörer',
    t12: '.',
  }, {
    t0: 'Начальник дал поручение проверить все документы. (Chef Auftrag Dokumente)',
    t1: 'Der',
    t2: 'Chef',
    t3: 'hat',
    t4: 'den',
    t5: 'Auftrag',
    t6: 'gegeben',
    t7: 'alle',
    t8: 'Dokumente',
    t9: 'zu',
    t10: 'überprüfen',
    t11: '.',

  }, {
    t0: 'Он выразил свою обеспокоенность на встрече. (Meeting Besorgnis Ausdruck)',
    t1: 'Er',
    t2: 'brachte',
    t3: 'im',
    t4: 'Meeting',
    t5: 'seine',
    t6: 'Besorgnis',
    t7: 'zum',
    t8: 'Ausdruck',
    t9: '.',
  },
  {
    t0: 'Сегодня существует множество перспективных профессий на выбор. (zukunftsweisende Berufe zur Auswahl)',
    t1: 'Heute',
    t2: 'stehen',
    t3: 'viele',
    t4: 'zukunftsweisende',
    t5: 'Berufe',
    t6: 'zur',
    t7: 'Auswahl',
    t8: '.',

  }, {
    t0: 'Работы по техническому обслуживанию оказывают влияние на весь процесс эксплуатации. (Wartungsarbeiten Auswirkungen Betrieb)',
    t1: 'Die',
    t2: 'Wartungsarbeiten',
    t3: 'haben',
    t4: 'Auswirkungen',
    t5: 'auf',
    t6: 'den',
    t7: 'gesamten',
    t8: 'Betrieb',
    t9: '.',
  }, {
    t0: 'Альтернативные модели работы в настоящее время привлекают большое внимание. (Alternative Arbeitsmodelle   Beachtung)',
    t1: 'Alternative',
    t2: 'Arbeitsmodelle',
    t3: 'finden',
    t4: 'momentan',
    t5: 'große',
    t6: 'Beachtung',
    t7: '.',
  }, {
    t0: 'Каждый может внести свой вклад в улучшение рабочих процессов. ( Beitrag zu Verbesserung der Arbeitsabläufe )',
    t1: 'Jeder',
    t2: 'kann',
    t3: 'einen',
    t4: 'Beitrag',
    t5: 'zu',
    t6: 'Verbesserung',
    t7: 'der',
    t8: 'Arbeitsabläufe',
    t9: 'leisten',
    t10: '.',
  }, {
    t0: 'Ивонн работает социальным работником уже 20 лет. (Beruf Sozialarbeiter Jahren)',
    t1: 'Yvonne',
    t2: 'übt',
    t3: 'seinen',
    t4: 'Beruf',
    t5: 'als',
    t6: 'Sozialarbeiter',
    t7: 'schon',
    t8: 'seit',
    t9: '20',
    t10: 'Jahren',
    t11: 'aus',
    t12: '.',
  }, {
    t0: 'Я всегда хотел получить профессию в отеле. (Beruf Hotel)',
    t1: 'Ich',
    t2: 'wollte',
    t3: 'schon',
    t4: 'immer',
    t5: 'einen',
    t6: 'Beruf',
    t7: 'im',
    t8: 'Hotel',
    t9: 'ergreifen',
    t10: '.',

  }, {
    t0: 'Не могли бы вы сообщить мне, пожалуйста, если база данных обновлена. (Bescheid Datenbank aktualisiert)',
    t1: 'Können',
    t2: 'Sie',
    t3: 'mir',
    t4: 'bitte',
    t5: 'Bescheid',
    t6: 'geben',
    t7: 'wenn',
    t8: 'die',
    t9: 'Datenbank',
    t10: 'aktualisiert',
    t11: 'ist',
    t12: '.',

  }, {
    t0: 'Многие люди все еще слишком мало знают о правах трудящихся. (Rechte Arbeitsnehmenden Bescheid)',
    t1: 'Über',
    t2: 'die',
    t3: 'Rechte',
    t4: 'von',
    t5: 'Arbeitsnehmenden',
    t6: 'wissen',
    t7: 'viele',
    t8: 'immer',
    t9: 'noch',
    t10: 'zu',
    t11: 'wenig',
    t12: 'Bescheid',
    t13: '.',
  }, {
    t0: 'Мы уже разместили наш заказ час назад и все еще ждем. (Bestellung Stunde)',
    t1: 'Wir',
    t2: 'haben',
    t3: 'unsere',
    t4: 'Bestellung',
    t5: 'bereits',
    t6: 'vor',
    t7: 'einer',
    t8: 'Stunde',
    t9: 'aufgegeben',
    t10: 'und',
    t11: 'warten',
    t12: 'immer',
    t13: 'noch',
    t14: '.',
  }, {
    t0: 'Для решения проблемы рассматривается несколько вариантов. (Lösung Problems Möglichkeiten in Betracht)',
    t1: 'Zur',
    t2: 'Lösung',
    t3: 'des',
    t4: 'Problems',
    t5: 'kommen',
    t6: 'mehrere',
    t7: 'Möglichkeiten',
    t8: 'in',
    t9: 'Betracht',
    t10: '.',

  }, {
    t0: 'Многие люди рассматривают возможность переезда из-за работы. (Leute  in Betracht  Arbeitsstelle)',
    t1: 'Viele',
    t2: 'Leute',
    t3: 'sehen',
    t4: 'in',
    t5: 'Betracht',
    t6: 'wegen',
    t7: 'einer',
    t8: 'Arbeitsstelle',
    t9: 'umzuziehen',
    t10: '.',
  }, {
    t0: 'С сегодняшнего дня в офисе введена в эксплуатацию новая система вентиляции. (Büro Lüftungsanlage in Betrieb)',
    t1: 'Seit',
    t2: 'heute',
    t3: 'ist',
    t4: 'im',
    t5: 'Büro',
    t6: 'die',
    t7: 'neue',
    t8: 'Lüftungsanlage',
    t9: 'in',
    t10: 'Betrieb',
    t11: '.',
  }, {
    t0: 'Я ссылаюсь на ваше письмо от 13 февраля. (Bezug Schreiben Februar)',
    t1: 'Ich',
    t2: 'nehme',
    t3: 'Bezug',
    t4: 'auf',
    t5: 'Ihr',
    t6: 'Schreiben',
    t7: 'vom',
    t8: '13',
    t9: '.',
    t10: 'Februar',
    t11: '.',
  }, {
    t0: 'Новому руководителю еще предстоит доказать свои знания. (Chefin Beweis)',
    t1: 'In',
    t2: 'die',
    t3: 'neue',
    t4: 'Chefin',
    t5: 'muss',
    t6: 'ihr',
    t7: 'kennen',
    t8: 'erst',
    t9: 'noch',
    t10: 'unter',
    t11: 'Beweis',
    t12: 'stellen',
    t13: '.',
  }, {
    t0: 'Различные решения доступны для обсуждения. (Verschiedene Lösungen Diskussion)',
    t1: 'Verschiedene',
    t2: 'Lösungen',
    t3: 'stehen',
    t4: 'zur',
    t5: 'Diskussion',
    t6: '.',
  }, {
    t0: 'Рабочие сегодня находятся в крайне тяжелом положении. (Arbeitnehmende Unterburg)',
    t1: 'Arbeitnehmende',
    t2: 'stehen',
    t3: 'heute',
    t4: 'enorm',
    t5: 'Unterburg',
    t6: '.',
  }, {
    t0: 'Преданность всей команды производит на меня большое впечатление. (Engagement Teams Eindruck)',
    t1: 'Das',
    t2: 'Engagement',
    t3: 'des',
    t4: 'ganzen',
    t5: 'Teams',
    t6: 'macht',
    t7: 'großen',
    t8: 'Eindruck',
    t9: 'auf',
    t10: 'mich',
    t11: '.',

  }, {
    t0: 'Я не хочу влиять на это решение. (Entscheidung Einfluss)',
    t1: 'Ich',
    t2: 'möchte',
    t3: 'auf',
    t4: 'diese',
    t5: 'Entscheidung',
    t6: 'keinen',
    t7: 'Einfluss',
    t8: 'nehmen',
    t9: '.',
  }, {
    t0: 'Мы должны, наконец, положить конец реструктуризации. (Umstrukturierung Ende)',
    t1: 'Wir',
    t2: 'müssen',
    t3: 'die',
    t4: 'Umstrukturierung',
    t5: 'endlich',
    t6: 'zu',
    t7: 'Ende',
    t8: 'bringen',
    t9: '.',
  }, {
    t0: 'Я наконец принял решение уволиться. (Entschluss)',
    t1: 'Ich',
    t2: 'habe',
    t3: 'endlich',
    t4: 'den',
    t5: 'Entschluss',
    t6: 'gefasst',
    t7: 'zu',
    t8: 'kündigen',
    t9: '.',
  }, {
    t0: 'Вы уже приняли решение по поводу новой должности? (Stelle Entscheidung)',
    t1: 'Haben',
    t2: 'sie',
    t3: 'wegen',
    t4: 'der',
    t5: 'neuen',
    t6: 'Stelle',
    t7: 'schon',
    t8: 'eine',
    t9: 'Entscheidung',
    t10: 'getroffen',
    t11: '?',
  }, {
    t0: 'Мое заветное желание сбылось. (Wunsch Erfüllung)',
    t1: 'Mein',
    t2: 'gewürzter',
    t3: 'Wunsch',
    t4: 'ist',
    t5: 'in',
    t6: 'Erfüllung',
    t7: 'gegangen',
    t8: '.',
  }, {
    t0: 'Руководство компании выдало сотрудникам разрешение на работу в домашнем офисе. (Geschäftsführung Mitarbeitenden die Erlaubnis im Homeoffice)',
    t1: 'Die',
    t2: 'Geschäftsführung',
    t3: 'erstellte',
    t4: 'den',
    t5: 'Mitarbeitenden',
    t6: 'die',
    t7: 'Erlaubnis',
    t8: 'im',
    t9: 'Homeoffice',
    t10: 'zu',
    t11: 'arbeiten',
    t12: '.',
  }, {
    t0: 'Я совершил ошибку, когда взял отпуск без консультации. (Fehler Rücksprache)',
    t1: 'Ich',
    t2: 'beging',
    t3: 'einen',
    t4: 'Fehler',
    t5: ',',
    t6: 'als',
    t7: 'ich',
    t8: 'mir',
    t9: 'ohne',
    t10: 'Rücksprache',
    t11: 'Urlaub',
    t12: 'nahm',
    t13: '.',
  }, {
    t0: 'Развитие последних лет привело к тому, что мы открываем новые рынки. (Entwicklung Jahre Folge Märkte)',
    t1: 'Die',
    t2: 'Entwicklung',
    t3: 'der',
    t4: 'letzten',
    t5: 'Jahre',
    t6: 'hat',
    t7: 'zur',
    t8: 'Folge',
    t9: 'dass',
    t10: 'wir',
    t11: 'neue',
    t12: 'Märkte',
    t13: 'erschließen',
    t14: '.',
  }, {
    t0: 'Он предъявляет очень много требований. (Forderungen)',
    t1: 'Er',
    t2: 'stellt',
    t3: 'ganz',
    t4: 'schön',
    t5: 'viele',
    t6: 'Forderungen',
    t7: '.',

  }, {
    t0: 'На семинаре мы рассмотрим вопрос о том, как лучше всего справляться со стрессом на работе. (Seminar Fragen Arbeitsstress)',
    t1: 'Im',
    t2: 'Seminar',
    t3: 'gehen',
    t4: 'wir',
    t5: 'in',
    t6: 'der',
    t7: 'Fragen',
    t8: 'nach',
    t9: ',',
    t10: 'wie',
    t11: 'man',
    t12: 'mit',
    t13: 'Arbeitsstress',
    t14: 'am',
    t15: 'besten',
    t16: 'umgeht',
    t17: '.',
  }, {
    t0: 'У него нет сомнений в том, что новые технологии важны для экономики. (Frage Technologien Wirtschaft)',
    t1: 'Er',
    t2: 'steht',
    t3: 'außer',
    t4: 'Frage',
    t5: ',',
    t6: 'dass',
    t7: 'neue',
    t8: 'Technologien',
    t9: 'für',
    t10: 'die',
    t11: 'Wirtschaft',
    t12: 'wichtig',
    t13: 'sind',
    t14: '.',
  }, {
    t0: 'Извините, могу я задать вам вопрос? (Entschuldigung Frage)',
    t1: 'Entschuldigung',
    t2: ',',
    t3: 'kann',
    t4: 'ich',
    t5: 'Ihnen',
    t6: 'eine',
    t7: 'Frage',
    t8: 'stellen',
    t9: '?',
  },
  {
    t0: 'Я много думаю о своем профессиональном будущем. (Gedanken Zukunft)',
    t1: 'Ich',
    t2: 'mache',
    t3: 'mir',
    t4: 'viele',
    t5: 'Gedanken',
    t6: 'über',
    t7: 'meine',
    t8: 'berufliche',
    t9: 'Zukunft',
    t10: '.',
  }, {
    t0: 'Реализация проекта находится под угрозой. (Realisierung Projekts Gefahr)',
    t1: 'Die',
    t2: 'Realisierung',
    t3: 'des',
    t4: 'Projekts',
    t5: 'ist',
    t6: 'in',
    t7: 'Gefahr',
    t8: '.',
  }, {
    t0: 'У вас уже была возможность связаться с IT. (Gelegenheit verständigen)',
    t1: 'Hatten',
    t2: 'sie',
    t3: 'bereits',
    t4: 'Gelegenheit',
    t5: 'sich',
    t6: 'mit',
    t7: 'der',
    t8: 'IT',
    t9: 'zu',
    t10: 'verständigen',
    t11: '.',
  }, {
    t0: 'у нас состоялся интересный разговор с компанией-партнером о новом проекте. (Partnerfirma Gespräch Projekt)',
    t1: 'Wir',
    t2: 'haben',
    t3: 'mit',
    t4: 'der',
    t5: 'Partnerfirma',
    t6: 'ein',
    t7: 'interessantes',
    t8: 'Gespräch',
    t9: 'über',
    t10: 'das',
    t11: 'neue',
    t12: 'Projekt',
    t13: 'geführt',
    t14: '.',
  }, {
    t0: 'Никаких причин для этого решения не было предоставлено. (Entscheidung Gründe)',
    t1: 'Für',
    t2: 'diese',
    t3: 'Entscheidung',
    t4: 'wurden',
    t5: 'keine',
    t6: 'Gründe',
    t7: 'angegeben',
    t8: '.',
  }, {
    t0: 'Не отвечать на приветствие, считается очень грубым. (Gruß )',
    t1: 'Einen',
    t2: 'Gruß',
    t3: 'nicht',
    t4: 'zu',
    t5: 'erwidern',
    t6: ',',
    t7: 'gilt',
    t8: 'als',
    t9: 'sehr',
    t10: 'unhöflich',
    t11: '.',
  }, {
    t0: 'Я был бы рад, если бы мне удалось заинтересовать вас нашими новыми продуктами. (Interesse Produkte)',
    t1: 'Es',
    t2: 'freut',
    t3: 'mich',
    t4: ',',
    t5: 'wenn',
    t6: 'ich',
    t7: 'Ihr',
    t8: 'Interesse',
    t9: 'für',
    t10: 'unsere',
    t11: 'neuen',
    t12: 'Produkte',
    t13: 'wecken',
    t14: 'konnte',
    t15: '.',
  }, {
    t0: 'Тот, кто переходит на эту должность, принимает на себя определенные риски. (Stelle Risiken in Kauf)',
    t1: 'Wer',
    t2: 'in',
    t3: 'die',
    t4: 'Stelle',
    t5: 'wechselt',
    t6: ',',
    t7: 'nimmt',
    t8: 'einige',
    t9: 'Risiken',
    t10: 'in',
    t11: 'Kauf',
    t12: '.',
  },
  {
    t0: 'Пожалуйста, примите к сведению, что частное использование Интернета в рабочее время запрещено. (Kenntnis Nutzung Internets Arbeitszeit)',
    t1: 'Bitte',
    t2: 'nehmen',
    t3: 'Sie',
    t4: 'zur',
    t5: 'Kenntnis',
    t6: ',',
    t7: 'dass',
    t8: 'die',
    t9: 'private',
    t10: 'Nutzung',
    t11: 'des',
    t12: 'Internets',
    t13: 'während',
    t14: 'der',
    t15: 'Arbeitszeit',
    t16: 'verboten',
    t17: 'ist',
    t18: '.',
  }, {
    t0: 'На выставке можно легко связаться с новыми клиентами. (Messe Kunden Kontakt)',
    t1: 'Auf',
    t2: 'einer',
    t3: 'Messe',
    t4: 'kann',
    t5: 'man',
    t6: 'gut',
    t7: 'mit',
    t8: 'neuen',
    t9: 'Kunden',
    t10: 'Kontakt',
    t11: 'aufnehmen',
    t12: '.',

  }, {
    t0: 'Она уже вступила в контакт с заявителем? (Bewerber Kontakt)',
    t1: 'Ist',
    t2: 'sie',
    t3: 'schon',
    t4: 'mit',
    t5: 'dem',
    t6: 'Bewerber',
    t7: 'in',
    t8: 'Kontakt',
    t9: 'getreten',
    t10: '?',
  }, {
    t0: 'Кто несет расходы по несчастному случаю на производстве? (Kosten des Arbeitsunfalls)',
    t1: 'Wer',
    t2: 'trägt',
    t3: 'die',
    t4: 'Kosten',
    t5: 'des',
    t6: 'Arbeitsunfalls',
    t7: '?',
  }, {
    t0: 'Нынешняя минимальная заработная плата подвергается большой критике. (Mindestlohn Kritik)',
    t1: 'An',
    t2: 'derzeitigen',
    t3: 'Mindestlohn',
    t4: 'wird',
    t5: 'viel',
    t6: 'Kritik',
    t7: 'geübt',
    t8: '.',
  }, {
    t0: 'Я сейчас не в состоянии, ясно мыслить. (Lage)',
    t1: 'Ich',
    t2: 'bin',
    t3: 'gerade',
    t4: 'nicht',
    t5: 'in',
    t6: 'der',
    t7: 'Lage',
    t8: ',',
    t9: 'klar',
    t10: 'zu',
    t11: 'denken',
    t12: '.',
  }, {
    t0: 'Не всегда легко, поддерживать светскую беседу. (Small Talk am Laufen)',
    t1: 'Es',
    t2: 'ist',
    t3: 'nicht',
    t4: 'immer',
    t5: 'einfach',
    t6: ',',
    t7: 'Small',
    t8: 'Talk',
    t9: 'am',
    t10: 'Laufen',
    t11: 'zu',
    t12: 'halten',
    t13: '.',
  }, {
    t0: 'Ты в курсе последних событий? (Entwicklungen Laufenden)',
    t1: 'Bist',
    t2: 'du',
    t3: 'über',
    t4: 'die',
    t5: 'neuesten',
    t6: 'Entwicklungen',
    t7: 'auf',
    t8: 'dem',
    t9: 'Laufenden',
    t10: '?',
  }, {
    t0: 'Все новые и новые устройства выводятся на рынок. (Geräte Markt)',
    t1: 'Immer',
    t2: 'neue',
    t3: 'Geräte',
    t4: 'werden',
    t5: 'auf',
    t6: 'den',
    t7: 'Markt',
    t8: 'gebracht',
    t9: '.',
  }, {
    t0: 'Он действительно старается, быстро изучить все рабочие процессы. (Mühe Arbeitsabläufe)',
    t1: 'Er',
    t2: 'gibt',
    t3: 'sich',
    t4: 'wirklich',
    t5: 'Mühe',
    t6: ',',
    t7: 'alle',
    t8: 'Arbeitsabläufe',
    t9: 'schnell',
    t10: 'zu',
    t11: 'lernen',
    t12: '.',
  }, {
    t0: 'Эти постоянные встречи действительно действуют мне на нервы. (ständigen Besprechungen Nerven)',
    t1: 'Diese',
    t2: 'ständigen',
    t3: 'Besprechungen',
    t4: 'gehen',
    t5: 'mir',
    t6: 'wirklich',
    t7: 'auf',
    t8: 'die',
    t9: 'Nerven',
    t10: '.',
  }, {
    t0: 'Несмотря на множество неудач он продолжал придерживаться своих планов. (Misserfolge Plänen)',
    t1: 'Trotz',
    t2: 'vieler',
    t3: 'Misserfolge',
    t4: 'hielt',
    t5: 'er',
    t6: 'an',
    t7: 'seinen',
    t8: 'Plänen',
    t9: 'fest',
    t10: '.',
  }, {
    t0: 'В конце обучения необходимо сдать практический экзамен. (Ausbildung Prüfung)',
    t1: 'Am',
    t2: 'Ende',
    t3: 'der',
    t4: 'Ausbildung',
    t5: 'muss',
    t6: 'man',
    t7: 'eine',
    t8: 'praktische',
    t9: 'Prüfung',
    t10: 'ablegen',
    t11: '.',
  }, {
    t0: 'Важно также проявлять уважение к конкурентам. (Konkurrenz Respekt entgegenzubringen)',
    t1: 'Es',
    t2: 'ist',
    t3: 'wichtig',
    t4: 'auch',
    t5: 'der',
    t6: 'Konkurrenz',
    t7: 'Respekt',
    t8: 'entgegenzubringen',
    t9: '.',
  }, {
    t0: 'Конкуренция играет большую роль во многих проблемах в команде. (Problemen im Team Konkurrenz Rolle)',
    t1: 'Bei',
    t2: 'vielen',
    t3: 'Problemen',
    t4: 'im',
    t5: 'Team',
    t6: 'spielt',
    t7: 'Konkurrenz',
    t8: 'eine',
    t9: 'große',
    t10: 'Rolle',
    t11: '.',
  }, {
    t0: 'Пожалуйста дайте мне еще отзыв о предложенной дате в 23. (Rückmeldung vorgeschlagenen Termin)',
    t1: 'Bitte',
    t2: 'geben',
    t3: 'Sie',
    t4: 'mir',
    t5: 'noch',
    t6: 'Rückmeldung',
    t7: 'von',
    t8: 'vorgeschlagenen',
    t9: 'Termin',
    t10: 'in',
    t11: '23',
    t12: '.',
  }, {
    t0: 'Важно, проявлять уважение ко всей команде. (Rücksicht Team)',
    t1: 'Es',
    t2: 'ist',
    t3: 'wichtig',
    t4: ',',
    t5: 'Rücksicht',
    t6: 'auf',
    t7: 'das',
    t8: 'ganze',
    t9: 'Team',
    t10: 'zu',
    t11: 'nehmen',
    t12: '.',
  }, {
    t0: 'Разговаривая с рассерженными клиентами, вы должны, прежде всего, сохранять спокойствие. (Gespräch Kunden Ruhe bewahren)',
    t1: 'Im',
    t2: 'Gespräch',
    t3: 'mit',
    t4: 'verärgerten',
    t5: 'Kunden',
    t6: 'sollten',
    t7: 'Sie',
    t8: 'vor',
    t9: 'allem',
    t10: 'Ruhe',
    t11: 'bewahren',
    t12: '.',
  }, {
    t0: 'Это было нехорошо, но ты уже снова берешь их под свою защиту. (Ordnung Schutz)',
    t1: 'Das',
    t2: 'war',
    t3: 'nicht',
    t4: 'in',
    t5: 'Ordnung',
    t6: ',',
    t7: 'aber',
    t8: 'du',
    t9: 'nimmst',
    t10: 'sie',
    t11: 'schon',
    t12: 'wieder',
    t13: 'in',
    t14: 'Schutz',
    t15: '.',
  }, {
    t0: 'Я очень обеспокоен и будущим компании. (Sorgen Zukunft Firma)',
    t1: 'Ich',
    t2: 'mache',
    t3: 'mir',
    t4: 'große',
    t5: 'Sorgen',
    t6: 'und',
    t7: 'die',
    t8: 'Zukunft',
    t9: 'der',
    t10: 'Firma',
    t11: '.',

  }, {
    t0: 'Мы не должны ставить под угрозу удовлетворение клиента. (Zufriedenheit Kundin aufs Spiel)',
    t1: 'Wir',
    t2: 'dürfen',
    t3: 'die',
    t4: 'Zufriedenheit',
    t5: 'der',
    t6: 'Kundin',
    t7: 'nicht',
    t8: 'aufs',
    t9: 'Spiel',
    t10: 'setzen',
    t11: '.',
  }, {
    t0: 'Конфликты следует решать быстро. (Konflikte Sprache gebracht)',
    t1: 'Konflikte',
    t2: 'sollten',
    t3: 'schnell',
    t4: 'zur',
    t5: 'Sprache',
    t6: 'gebracht',
    t7: 'werden',
    t8: '.',
  }, {
    t0: 'Важно, чтобы проблемы внутри команды наконец обсуждались. (Probleme Team Sprache)',
    t1: 'Es',
    t2: 'ist',
    t3: 'wichtig',
    t4: ',',
    t5: 'dass',
    t6: 'die',
    t7: 'Probleme',
    t8: 'im',
    t9: 'Team',
    t10: 'endlich',
    t11: 'zur',
    t12: 'Sprache',
    t13: 'kommen',
    t14: '.',
  }, {
    t0: 'Как продвигается проект? Можете ли вы ввести меня в курс дела? (Projekt Stand)',
    t1: 'Wie',
    t2: 'läuft',
    t3: 'das',
    t4: 'Projekt',
    t5: '?',
    t6: 'Können',
    t7: 'Sie',
    t8: 'mich',
    t9: 'auf',
    t10: 'den',
    t11: 'neuesten',
    t12: 'denn',
    t13: 'Stand',
    t14: 'bringen',
    t15: '?',
  }, {
    t0: 'Я придерживаюсь той точки зрения, что нам срочно нужна дополнительная поддержка. (Standpunkt Unterstützung)',
    t1: 'Ich',
    t2: 'stehe',
    t3: 'auf',
    t4: 'dem',
    t5: 'Standpunkt',
    t6: ',',
    t7: 'dass',
    t8: 'wir',
    t9: 'dringend',
    t10: 'mehr',
    t11: 'Unterstützung',
    t12: 'brauchen',
    t13: '.',
  }, {
    t0: 'Я не хочу комментировать этот вопрос. (Sache Stellung)',
    t1: 'Ich',
    t2: 'möchte',
    t3: 'zu',
    t4: 'dieser',
    t5: 'Sache',
    t6: 'keine',
    t7: 'Stellung',
    t8: 'nehmen',
    t9: '.',
  }, {
    t0: 'Какие внутренние договоренности по контракту были достигнуты с вами? (Verabredungen Vertrag)',
    t1: 'Welche',
    t2: 'internen',
    t3: 'Verabredungen',
    t4: 'zum',
    t5: 'Vertrag',
    t6: 'wurden',
    t7: 'denn',
    t8: 'mit',
    t9: 'Ihnen',
    t10: 'getroffen',
    t11: '?',
  }, {
    t0: 'Работодатель несет ответственность за здоровье сотрудников. (Arbeitsgeber Verantwortung Gesundheit Mitarbeitenden)',
    t1: 'Der',
    t2: 'Arbeitsgeber',
    t3: 'trägt',
    t4: 'die',
    t5: 'Verantwortung',
    t6: 'für',
    t7: 'die',
    t8: 'Gesundheit',
    t9: 'der',
    t10: 'Mitarbeitenden',
    t11: '.',
  }, {
    t0: 'Обращайтесь в IT при возникновении технических проблем. (IT Problemen Verbindung)',
    t1: 'Setzen',
    t2: 'Sie',
    t3: 'sich',
    t4: 'bei',
    t5: 'technischen',
    t6: 'Problemen',
    t7: 'mit',
    t8: 'der',
    t9: 'IT',
    t10: 'in',
    t11: 'Verbindung',
    t12: '.',
  }, {
    t0: 'Своими вопросами он поставил меня в неловкое положение. (Fragen Verlegenheit)',
    t1: 'Mit',
    t2: 'seinen',
    t3: 'Fragen',
    t4: 'hat',
    t5: 'er',
    t6: 'mich',
    t7: 'in',
    t8: 'Verlegenheit',
    t9: 'gebracht',
    t10: '.',
  }, {
    t0: 'На проект не хватает денег. (Projekt Geld zur Verfügung)',
    t1: 'Für',
    t2: 'das',
    t3: 'Projekt',
    t4: 'steht',
    t5: 'nicht',
    t6: 'genug',
    t7: 'Geld',
    t8: 'zur',
    t9: 'Verfügung',
    t10: '.',
  }, {
    t0: 'Мы будем рады предоставить вам дополнительную документацию о процессе признания профессии. (Unterlagen Berufsanerkennungsverfahren Verfügung)',
    t1: 'Gerne',
    t2: 'stellen',
    t3: 'wir',
    t4: 'Ihnen',
    t5: 'weitere',
    t6: 'Unterlagen',
    t7: 'über',
    t8: 'das',
    t9: 'Berufsanerkennungsverfahren',
    t10: 'zu',
    t11: 'Verfügung',
    t12: '.',
  }, {
    t0: 'Я не могу понять эту проблему. (Problem Verständnis)',
    t1: 'Ich',
    t2: 'kann',
    t3: 'für',
    t4: 'dieses',
    t5: 'Problem',
    t6: 'kein',
    t7: 'Verständnis',
    t8: 'aufbringen',
    t9: '.',

  }, {
    t0: 'Если бы у меня был выбор, я бы всегда отдавал предпочтение работе с частичной занятостью. (die Wahl Teilzeitstelle Vorzug)',
    t1: 'Wenn',
    t2: 'ich',
    t3: 'die',
    t4: 'Wahl',
    t5: 'hätte',
    t6: ',',
    t7: 'würde',
    t8: 'ich',
    t9: 'einer',
    t10: 'Teilzeitstelle',
    t11: 'immer',
    t12: 'den',
    t13: 'Vorzug',
    t14: 'geben',
    t15: '.',

  },
  {
    t0: 'С тех пор как они поссорились он избегает его. (Streit aus dem Weg)',
    t1: 'Seit',
    t2: 'dem',
    t3: 'Streit',
    t4: 'geht',
    t5: 'er',
    t6: 'ihm',
    t7: 'aus',
    t8: 'dem',
    t9: 'Weg',
    t10: '.',
  }, {
    t0: 'Благополучие гостей в нашем отеле находится в центре внимания. (Wohl der Gäste Hotel im Zentrum)',
    t1: 'Das',
    t2: 'Wohl',
    t3: 'der',
    t4: 'Gäste',
    t5: 'steht',
    t6: 'in',
    t7: 'unserem',
    t8: 'Hotel',
    t9: 'im',
    t10: 'Zentrum',
    t11: '.',

  }, {
    t0: 'Показатели продаж напрямую связаны с маркетинговой акцией осенью. (Absatzzahlen direkten Zusammenhang  Marketing Aktion im Herbst)',
    t1: 'Die',
    t2: 'Absatzzahlen',
    t3: 'stehen',
    t4: 'im',
    t5: 'direkten',
    t6: 'Zusammenhang',
    t7: 'mit',
    t8: 'der',
    t9: 'Marketing',
    t10: 'Aktion',
    t11: 'im',
    t12: 'Herbst',
    t13: '.',

  }, {
    t0: 'У меня есть сомнения в эффективность временных рабочих мест. (Zweifel an das Wirksamkeit Arbeitsstellen)',
    t1: 'Ich',
    t2: 'habe',
    t3: 'Zweifel',
    t4: 'an',
    t5: 'das',
    t6: 'Wirksamkeit',
    t7: 'von',
    t8: 'befristeten',
    t9: 'Arbeitsstellen',
    t10: '.',

  }, {
    t0: 'Нет никаких сомнений в том, что мы не смогли бы работать так же хорошо без компьютеров. (Zweifel Computer)',
    t1: 'Es',
    t2: 'steht',
    t3: 'außer',
    t4: 'Zweifel',
    t5: ',',
    t6: 'dass',
    t7: 'wir',
    t8: 'ohne',
    t9: 'Computer',
    t10: 'nicht',
    t11: 'so',
    t12: 'gut',
    t13: 'arbeiten',
    t14: 'könnten',
    t15: '.',
  },
]


</script>

<style lang="scss" ></style>