<template lang="pug">
.container
  .page-title 
    h2 Nomen-Verb-Verbindungen

  .page-block
    .page-title--small 
      h2 Training
    TabsTraining( title='' :SlotData='SlotDativ' )


 
    
 
</template>
<script setup>
import Tabs from '@/components/Tabs.vue';
import TabsTraining from '@/components/TabsTraining.vue';
import Plaza from '@/components/Plaza.vue';
import Slot from '@/components/Slot.vue'

const SlotDativ = [
  {
    t0: 'Перед сложными контрактами следует остерегаться. (Vor Verträgen sollte man sich )',
    t1: 'Vor',
    t2: 'komplizierten',
    t3: 'Verträgen',
    t4: 'sollte',
    t5: 'man',
    t6: 'sich',
    t7: 'in',
    t8: 'Acht',
    t9: 'nehmen',
    t10: '.',

  }, {
    t0: 'Важно также проявлять уважение к конкурентам.(Konkurrenz )',
    t1: 'Es',
    t2: 'ist',
    t3: 'wichtig',
    t4: ',',
    t5: 'auch',
    t6: 'der',
    t7: 'Konkurrenz',
    t8: 'Achtung',
    t9: 'entgegenzubringen',
    t10: '.',

  }, {
    t0: 'У меня есть намерение сделать карьеру. (Absicht Karriere)',
    t1: 'Ich',
    t2: 'habe',
    t3: 'die',
    t4: 'Absicht',
    t5: ',',
    t6: 'Karriere',
    t7: 'zu',
    t8: 'machen',
    t9: '.',

  }, {
    t0: 'Все сотрудники могут в любое время изменить свой пароль. (Mitarbeitenden Passwort jederzeit)',
    t1: 'Аlle',
    t2: 'Mitarbeitenden',
    t3: 'können',
    t4: 'an',
    t5: 'ihrem',
    t6: 'Passwort',
    t7: 'jederzeit',
    t8: 'eine',
    t9: 'Änderung',
    t10: 'vornehmen',
    t11: '.',
  }, {
    t0: 'Достижения группы находят признание во всем мире. (Leistungen Konzerns weltweit Anerkennung)',
    t1: 'Die',
    t2: 'Leistungen',
    t3: 'des',
    t4: 'Konzerns',
    t5: 'finden',
    t6: 'weltweit',
    t7: 'Anerkennung',
    t8: '.',

  }, {
    t0: 'Марина отвечает всем требованиям, указанным в объявлении о вакансии. (Anforderungen Stellenausschreibung)',
    t1: 'Marina',
    t2: 'erfüllt',
    t3: 'alle',
    t4: 'Anforderungen',
    t5: 'in',
    t6: 'der',
    t7: 'Stellenausschreibung',
    t8: '.',
  }, {
    t0: 'Мы уже отправили запрос в ремесленную мастерскую на ремонтные работы. (Renovierungsarbeiten bereits Anfrage Handwerksbetrieb)',
    t1: 'Für',
    t2: 'die',
    t3: 'Renovierungsarbeiten',
    t4: 'haben',
    t5: 'wir',
    t6: 'bereits',
    t7: 'eine',
    t8: 'Anfrage',
    t9: 'an',
    t10: 'einen',
    t11: 'Handwerksbetrieb',
    t12: 'gestellt',
    t13: '.',

  }, {
    t0: 'Компания сделала мне отличное предложение. (Firma Angebot )',
    t1: 'Die',
    t2: 'Firma',
    t3: 'hat',
    t4: 'mir',
    t5: 'ein',
    t6: 'tolles',
    t7: 'Angebot',
    t8: 'gemacht',
    t9: '.',

  }, {
    t0: 'Я займусь заказом клиента прямо сейчас. (Bestellung Kunden Angriff)',
    t1: 'Ich',
    t2: 'werde',
    t3: 'die',
    t4: 'Bestellung',
    t5: 'des',
    t6: 'Kunden',
    t7: 'gleich',
    t8: 'in',
    t9: 'Angriff',
    t10: 'nehmen',
    t11: '.',

  }, {
    t0: 'Мысль о моем первом дне на работе пугает меня. (Gedanke Arbeitstag Angst)',
    t1: 'Der',
    t2: 'Gedanke',
    t3: 'an',
    t4: 'meinen',
    t5: 'ersten',
    t6: 'Arbeitstag',
    t7: 'macht',
    t8: 'mir',
    t9: 'Angst',
    t10: '.',

  }, {
    t0: 'Я очень обеспокоен тем, что этот вопрос будет решен быстро. (großes Anliegen Sache wird)',
    t1: 'Es',
    t2: 'ist',
    t3: 'mir',
    t4: 'ein',
    t5: 'großes',
    t6: 'Anliegen',
    t7: ',',
    t8: 'dass',
    t9: 'die',
    t10: 'Sache',
    t11: 'schnell',
    t12: 'geklärt',
    t13: 'wird',
    t14: '.',

  }, {
    t0: 'Вы имеете право на отпуск продолжительностью не менее 20 дней в году. (Anspruch Tage Urlaub)',
    t1: 'Sie',
    t2: 'haben',
    t3: 'Anspruch',
    t4: 'auf',
    t5: 'mindestens',
    t6: '20',
    t7: 'Tage',
    t8: 'Urlaub',
    t9: 'pro',
    t10: 'Jahr',
    t11: '.',

  }, {
    t0: 'мы должны использовать возможности финансирования через городской совет()',
    t1: 'wir sollten Fördermöglichkeiten durch den Stadt strärke in Anspruch nehmen',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'Мартина Морена подала заявку на учредительный грант()',
    t1: 'Martina Morena hat einen Antrag auf Gründungszuschuss gestellt',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'результаты совещаний часто не используются()',
    t1: 'die Ergebnisse aus Besprechungen kommen oft nicht zur Anwendung',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'список адресов ждет меня, я должен вернуться к работе()',
    t1: 'die Adressenliste wartet auf mich ich muss wieder an die Arbeit gehen',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'мы приобрели нового крупного клиента. вы, ребята, проделали очень хорошую работу()',
    t1: 'wir haben einen neuen großen Kunden gewonnen. ihr habt sehr gute Arbeit geleistet',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: '()',
    t1: 'die Pflege unserer Kundendaten macht viel Arbeit',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'пошли, перерыв окончен ! давайте вернемся к работе()',
    t1: 'komm, die Pause ist vorbei ! machen wir uns wieder an die Arbeit',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'где находится предложение для компании kraxel()',
    t1: 'wo ist das Angebot für die Firma kraxel',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'я пришел к выводу, что мы должны работать над компенсацией клиентам()',
    t1: 'ich bin zu der Auffassung gelernt dass wir der Kunden eine Entschädigung arbeiten sollten',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'с помощью небольшого анекдота вы легко завоюете внимание своих слушателей()',
    t1: 'mit einer kleinen Anekdote gewinnen sie leicht die Aufmerksamkeit ihrer Zuhörer',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'начальник дал поручение проверить все документы()',
    t1: 'der Chef hat den Auftrag gegeben alle Dokumente zu überprüfen',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'он выразил свою обеспокоенность на встрече()',
    t1: 'er brachte im Meeting seine Besorgnis zum Ausdruck',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  },
  {
    t0: 'сегодня существует множество перспективных профессий на выбор()',
    t1: 'heute stehen viele zukunftsweisende Berufe zur Auswahl',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'работы по техническому обслуживанию оказывают влияние на весь процесс эксплуатации()',
    t1: 'die Wartungsarbeiten haben Auswirkungen auf den gesamten Betrieb',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'альтернативные модели работы в настоящее время привлекают большое внимание()',
    t1: 'alternative Arbeitsmodelle finden momentan große Beachtung',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'каждый может внести свой вклад в улучшение рабочих процессов()',
    t1: 'jeder kann einen Beitrag zu Verbesserung der Arbeitsabläufe leisten',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'Ивонн работает социальным работником уже 20 лет()',
    t1: 'Yvonne übt seinen Beruf als Sozialarbeiter schon seit 20 Jahren aus',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'я всегда хотел получить профессию в отеле()',
    t1: 'ich wollte schon immer einen Beruf im Hotel ergreifen',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'не могли бы вы сообщить мне, пожалуйста, если база данных обновлена()',
    t1: 'können Sie mir bitte Bescheid geben wenn die Datenbank aktualisiert ist',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'многие люди все еще слишком мало знают о правах трудящихся()',
    t1: 'über die Rechte von Arbeitsnehmenden wissen viele immer noch zu wenig Bescheid',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'wir haben unsere Bestellung bereits vor einer Stunde aufgegeben und warten immer noch()',
    t1: 'wir haben unsere Bestellung bereits vor einer Stunde aufgegeмы уже разместили наш заказ час назад и все еще ждемben und warten immer noch',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'для решения проблемы рассматривается несколько вариантов()',
    t1: 'zur Lösung des Problems kommen mehrere Möglichkeiten in Betracht',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'многие люди рассматривают возможность переезда из-за работы()',
    t1: 'viele Leute sehen in Betracht wegen einer Arbeitsstelle umzuziehen',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'с сегодняшнего дня в офисе введена в эксплуатацию новая система вентиляции()',
    t1: 'seit heute ist im Büro die neue Lüftungsanlage in Betrieb',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'ich nehme Bezug auf Ihr Schreiben vom 13. Februar()',
    t1: 'я ссылаюсь на ваше письмо от 13 февраля',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'новому руководителю еще предстоит доказать свои знания()',
    t1: 'in die neue Chefin muss ihr kennen erst noch unter Beweis stellen',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'различные решения доступны для обсуждения()',
    t1: 'verschiedene Lösungen stehen zur Diskussion',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'Рабочие сегодня находятся в крайне тяжелом положении()',
    t1: 'Arbeitnehmende stehen heute enorm Unterburg',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'преданность всей команды производит на меня большое впечатление()',
    t1: 'das Engagement des ganzen Teams macht großen Eindruck auf mich',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'я не хочу влиять на это решение()',
    t1: 'ich möchte auf diese Entscheidung keinen Einfluss nehmen',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'мы должны, наконец, положить конец реструктуризации()',
    t1: 'wir müssen die Umstrukturierung endlich zu Ende bringen',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'я наконец принял решение уволиться()',
    t1: 'ich habe endlich den Entschluss gefasst zu kündigen',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'вы уже приняли решение по поводу новой должности?()',
    t1: 'haben sie wegen der neuen Stelle schon eine Entscheidung getroffen?',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'мое заветное желание сбылось()',
    t1: 'mein gewürzter Wunsch ist in Erfüllung gegangen',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'руководство компании выдало сотрудникам разрешение на работу в домашнем офисе()',
    t1: 'die Geschäftsführung erstellte den Mitarbeitenden die Erlaubnis im Homeoffice zu arbeiten',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'я совершил ошибку, когда взял отпуск без консультации()',
    t1: 'ich beging einen Fehler, als ich mir ohne Rücksprache Urlaub nahm',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'развитие последних лет привело к тому, что мы открываем новые рынки()',
    t1: 'die Entwicklung der letzten Jahre hat zur Folge dass wir neue Märkte erschließen',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'он предъявляет очень много требований()',
    t1: 'er stellt ganz schön viele Forderungen',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'на семинаре мы рассмотрим вопрос о том, как лучше всего справляться со стрессом на работе()',
    t1: 'im Seminar gehen wir in der Fragen nach, wie man mit Arbeitsstress am besten umgeht',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'у него нет сомнений в том, что новые технологии важны для экономики()',
    t1: 'er steht außer Frage, dass neue Technologien für die Wirtschaft wichtig sind',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'Извините, могу я задать вам вопрос?()',
    t1: 'Entschuldigung, kann ich Ihnen eine Frage stellen?',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'я много думаю о своем профессиональном будущем()',
    t1: 'ich mache mir viele Gedanken über meine berufliche Zukunft',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'реализация проекта находится под угрозой()',
    t1: 'die Realisierung des Projekts ist in Gefahr',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'у вас уже была возможность связаться с идентификатором()',
    t1: 'hatten sie bereits Gelegenheit sich mit der ID zu verständigen',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'у нас состоялся интересный разговор с компанией-партнером о новом проекте()',
    t1: 'wir haben mit der Partnerfirma ein interessantes Gespräch über das neue Projekt geführt',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'никаких причин для этого решения не было предоставлено()',
    t1: 'für diese Entscheidung wurden keine Gründe angegeben',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'не отвечать на приветствие считается очень грубым()',
    t1: 'einen Gruß nicht zu erwidern, gilt als sehr unhöflich',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'я был бы рад, если бы мне удалось заинтересовать вас нашими новыми продуктами()',
    t1: 'es freut mich wenn ich Ihr Interesse für unsere neuen Produkte wecken konnte',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'тот, кто переходит на эту должность, принимает на себя определенные риски()',
    t1: 'wer in die Stelle wechselt nimmt einige Risiken in Kauf',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  },
  {
    t0: 'пожалуйста, примите к сведению, что частное использование Интернета в рабочее время запрещено()',
    t1: 'bitte nehmen Sie zur Kenntnis, dass die private Nutzung des Internets während der Arbeitszeit verboten ist',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'на выставке можно легко связаться с новыми клиентами()',
    t1: 'auf einer Messe kann man gut mit neuen Kunden Kontakt aufnehmen',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'она уже вступила в контакт с заявителем?()',
    t1: 'ist sie schon mit dem Bewerber in Kontakt getreten?',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'кто несет расходы по несчастному случаю на производстве?()',
    t1: 'wer trägt die Kosten des Arbeitsunfalls?',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'нынешняя минимальная заработная плата подвергается большой критике()',
    t1: 'an derzeitigen Mindestlohn wird viel Kritik geübt',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'я сейчас не в состоянии ясно мыслить()',
    t1: 'ich bin gerade nicht in der Lage, klar zu denken',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'не всегда легко поддерживать светскую беседу()',
    t1: 'es ist nicht immer einfach Small talk am Laufen zu halten',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'ты в курсе последних событий?()',
    t1: 'bist du über die neuesten Entwicklungen auf dem Laufenden?',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'все новые и новые устройства выводятся на рынок()',
    t1: 'immer neue Geräte werden auf den Markt gebracht',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'он действительно старается быстро изучить все рабочие процессы()',
    t1: 'er gibt sich wirklich Mühe, alle Arbeitsabläufe schnell zu lernen',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'эти постоянные встречи действительно действуют мне на нервы()',
    t1: 'diese ständigen Besprechungen gehen mir wirklich auf die Nerven',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'несмотря на множество неудач, он продолжал придерживаться своих планов()',
    t1: 'trotz vieler Misserfolge hielt er an seinen Plänen fest',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'в конце обучения необходимо сдать практический экзамен()',
    t1: 'am Ende der Ausbildung muss man eine praktische Prüfung ablegen',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'важно также проявлять уважение к конкурентам()',
    t1: 'es ist wichtig auch der Konkurrenz Respekt entgegenzubringen',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'конкуренция играет большую роль во многих проблемах в команде()',
    t1: 'bei vielen Problemen im Team spielt Konkurrenz eine große Rolle',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'пожалуйста, дайте мне еще отзыв о предложенной дате в 23()',
    t1: 'bitte geben Sie mir noch Rückmeldung von vorgeschlagenen Termin in 23',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'важно проявлять уважение ко всей команде()',
    t1: 'es ist wichtig , Rücksicht auf das ganze Team zu nehmen',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'разговаривая с сержем о клиентах, вы должны, прежде всего, сохранять спокойствие()',
    t1: 'im Gespräch mit serrege von Kunden sollten Sie vor allem Ruhe bewahren',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'это было нехорошо, но ты уже снова берешь их под свою защиту()',
    t1: 'das war nicht in Ordnung,  aber du nimmst sie schon wieder in Schutz',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'я очень обеспокоен и будущим компании()',
    t1: 'ich mache mir große Sorgen und die Zukunft der Firma',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'мы не должны ставить под угрозу удовлетворение клиента()',
    t1: 'wir dürfen die Zufriedenheit der Kundin nicht aufs Spiel setzen',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'Конфликты следует решать быстро()',
    t1: 'Konflikte sollten schnell zur Sprache gebracht werden',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'Важно, чтобы проблемы внутри команды наконец обсуждались.()',
    t1: 'es ist wichtig dass die Probleme im Team endlich zur Spraches ist wichtig dass die Probleme im Team endlich zur Sprache kommene kommen',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'как продвигается проект? Можете ли вы ввести меня в курс дела?()',
    t1: 'wie läuft das Projekt? Können Sie mich auf den neuesten denn Stand bringen?',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'я придерживаюсь той точки зрения, что нам срочно нужна дополнительная поддержка()',
    t1: 'ich stehe auf dem Standpunkt, dass wir dringend mehr Unterstützung brauchen',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'я не хочу комментировать этот вопрос()',
    t1: 'ich möchte zu dieser Sache keine Stellung nehmen',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'Какие внутренние договоренности по контракту были достигнуты с вами?()',
    t1: 'Welche internen Verabredungen zum Vertrag wurden denn mit Ihnen getroffen?',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'работодатель несет ответственность за здоровье сотрудников()',
    t1: 'der Arbeitsgeber trägt die Verantwortung für die Gesundheit der Mitarbeitenden',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'обращайтесь в отдел информационных технологий при возникновении технических проблем()',
    t1: 'setzen Sie sich bei technischen Problemen mit der IT in Verbindung',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'своими вопросами он поставил меня в неловкое положение()',
    t1: 'mit seinen Fragen hat er mich in Verlegenheit gebracht',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'на проект не хватает денег()',
    t1: 'für das Projekt steht nicht genug Geld zur Verfügung',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'мы будем рады предоставить вам дополнительную документацию о процессе признания профессии()',
    t1: 'gerne stellen wir Ihnen weitere Unterlagen über das berufsanerkennungsverfahren zu Verfügung',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'я не могу понять эту проблему()',
    t1: 'ich kann für dieses Problem kein Verständnis aufbringen',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'если бы у меня был выбор, я бы всегда отдавал предпочтение работе с частичной занятостью()',
    t1: 'wenn ich die Wahl hätte, würde ich einer Teilzeitstelle  immer den Vorzug geben',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  },
  {
    t0: 'с тех пор, как они поссорились, он избегает его()',
    t1: 'seit dem Streit geht er ihm aus dem Weg',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'благополучие гостей в нашем отеле находится в центре внимания()',
    t1: 'das Wohl der Gäste steht in unserem Hotel im Zentrum',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'показатели продаж напрямую связаны с маркетинговой акцией осенью()',
    t1: 'die Absatzzahlen stehen im direkten Zusammenhang mit der Marketing Aktion im Herbst',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'у меня есть сомнения в эффективность временных рабочих мест()',
    t1: 'ich habe Zweifel an das Wirksamkeit von befristeten Arbeitsstellen',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  }, {
    t0: 'нет никаких сомнений в том, что мы не смогли бы работать так же хорошо без компьютеров()',
    t1: 'es steht außer Zweifel, dass wir ohne Computer nicht so gut arbeiten könnten',
    t2: '',
    t3: '',
    t4: '',
    t5: '',
    t6: '',
    t7: '',
    t8: '',
    t9: '',
    t10: '',
    t11: '',
    t12: '',
    t13: '',
    t14: '',
    t15: '',
    t16: '',
    t17: '',
    t18: '',
  },
]


</script>

<style lang="scss" ></style>