<template lang="pug">
.container
  .page-title 
    h2 Personalpronomen
  Tabs(:items= 'Personal' title='Personal' )
  .page-block
    .page-title--small 
      h3 Training
    Plaza
    Slot(:SlotData='SlotDataPersonal')





</template>


<script setup>
import { ref, computed } from 'vue';
// import Content from '@/components/Content.vue';
import Tabs from '@/components/Tabs.vue';

import Plaza from '@/components/Plaza.vue';
import Slot from '@/components/Slot.vue'

const Personal = ref([

  {
    title: 'Nominativ',
    text1: 'ich',
    text2: 'du',
    text3: 'er',
    text4: 'sie',
    text5: 'es',
    text6: 'wir',
    text7: 'ihr',
    text8: 'sie',
    text9: 'Sie',
    svg3: 'man',
    svg4: 'frau',
    svg5: 'das',
    svg6: 'group',
    svg7: 'group',
    svg8: 'group',
    svg9: 'respect',

  },
  {
    title: 'Dativ',
    text1: 'mir',
    text2: 'dir',
    text3: 'ihm',
    text4: 'ihr',
    text5: 'ihm',
    text6: 'uns',
    text7: 'euch',
    text8: 'ihnen',
    text9: 'Ihnen',
    svg3: 'man',
    svg4: 'frau',
    svg5: 'das',
    svg6: 'group',
    svg7: 'group',
    svg8: 'group',
    svg9: 'respect',
  },
  {
    title: 'Akkusativ',
    text1: 'mich',
    text2: 'dich',
    text3: 'ihn',
    text4: 'sie',
    text5: 'es',
    text6: 'uns',
    text7: 'euch',
    text8: 'sie',
    text9: 'Sie',
    svg3: 'man',
    svg4: 'frau',
    svg5: 'das',
    svg6: 'group',
    svg7: 'group',
    svg8: 'group',
    svg9: 'respect',
  },
  {
    title: 'Genitiv',
    text1: 'meiner',
    text2: 'deiner',
    text3: 'seiner',
    text4: 'ihrer',
    text5: 'seiner',
    text6: 'unser',
    text7: 'eurer',
    text8: 'ihrer',
    text9: 'Ihrer',
    svg3: 'man',
    svg4: 'frau',
    svg5: 'das',
    svg6: 'group',
    svg7: 'group',
    svg8: 'group',
    svg9: 'respect',
  },
])
const SlotDataPersonal = ref([
  {
    t0: 'Ты уже попросил Паули убрать его игрушки ? (Pauli gebeten seinen Spielzeug aufzuräumen)',
    t1: 'Hast',
    t2: 'du',
    t3: 'Pauli',
    t4: 'schon',
    t5: 'gebeten',
    t6: ',',
    t7: 'seinen',
    t8: 'Spielzeug',
    t9: 'aufzuräumen',
    t10: '?',
  },
  {
    t0: 'Я сказал ему, но он мне не подчиняется! (gesagt gehorcht)',
    t1: 'Ich',
    t2: 'habe',
    t3: 'es',
    t4: 'ihm',
    t5: 'gesagt',
    t6: ',',
    t7: 'aber',
    t8: 'er',
    t9: 'gehorcht',
    t10: 'mir',
    t11: 'nicht',
    t12: '!',
  },

  {
    t0: 'Не мог бы ты одолжить нам свое большое одеяло для пикника, чтобы нам не пришлось сидеть на мокрой траве? (Picknickdecke borgen nassen Gras sitzen müssen)',
    t1: 'Kannst',
    t2: 'du',
    t3: 'uns',
    t4: 'deine',
    t5: 'große',
    t6: 'Picknickdecke',
    t7: 'borgen',
    t8: ',',
    t9: 'damit',
    t10: 'wir',
    t11: 'nicht',
    t12: 'auf',
    t13: 'dem',
    t14: 'nassen',
    t15: 'Gras',
    t16: 'sitzen',
    t17: 'müssen',
    t18: '?',
  },


  {
    t0: 'Я знаю хорошего учителя, которому я мог бы его научить. (kenne Lehrerin vermitteln könnte)',
    t1: 'Ich',
    t2: 'kenne',
    t3: 'eine',
    t4: 'gute',
    t5: 'Lehrerin',
    t6: ',',
    t7: 'die',
    t8: 'ich',
    t9: 'ihm',
    t10: 'vermitteln',
    t11: 'könnte',
    t12: '.',

  },
  {
    t0: 'Я знаю хорошего учителя, которому я мог бы его научить. (kenne Lehrerin vermitteln könnte)',
    t1: 'Ich',
    t2: 'kenne',
    t3: 'eine',
    t4: 'gute',
    t5: 'Lehrerin',
    t6: ',',
    t7: 'die',
    t8: 'ich',
    t9: 'ihm',
    t10: 'vermitteln',
    t11: 'könnte',
    t12: '.',

  },
  {
    t0: 'Ты поможешь мне связаться с ней?(Hilfst kontaktieren)',
    t1: 'Hilfst',
    t2: 'du',
    t3: 'mir',
    t4: ',',
    t5: 'sie',
    t6: 'zu',
    t7: 'kontaktieren',
    t8: '?',
  },
  {
    t0: 'В процессе она потеряла свои ключи. (verlor Schlüssel)',
    t1: 'Dabei    ',
    t2: 'verlor',
    t3: 'sie',
    t4: 'ihre',
    t5: 'Schlüssel',
    t6: '.',

  },
  {
    t0: 'Тогда, пожалуйста, пусть мне его вернут! (Dann möge man wieder bringen)',
    t1: 'Dann',
    t2: 'möge',
    t3: 'man',
    t4: 'ihn',
    t5: 'mir',
    t6: 'bitte',
    t7: 'wieder',
    t8: 'bringen',
    t9: '!',
  },
  {
    t0: 'Мистер Монте, наш повар как раз готовит его, и мы сейчас принесем вам. (Monte Koch bereitet gerade zu bringen gleich)',
    t1: 'Herr',
    t2: 'Monte',
    t3: ',',
    t4: 'unser',
    t5: 'Koch',
    t6: 'bereitet',
    t7: 'es',
    t8: 'gerade',
    t9: 'zu',
    t10: 'und',
    t11: 'wir',
    t12: 'bringen',
    t12: 'es',
    t12: 'Ihnen',
    t12: 'gleich',
    t12: '.',

  },
  {
    t0: 'Я дам вам свои наклейки, а вы взамен отдадите мне свои стеклянные шарики.(gebe Sticker gebt Gegenzug Glasmurmeln)',
    t1: 'Ich',
    t2: 'gebe',
    t3: 'euch',
    t4: 'meine',
    t5: 'Sticker',
    t6: 'und',
    t7: 'ihr',
    t8: 'gebt',
    t9: 'mir',
    t10: 'im',
    t11: 'Gegenzug',
    t12: 'eure',
    t13: 'Glasmurmeln',
    t14: '.',
  },
  {
    t0: 'Завтра я встречаюсь с Кларой, она хочет мне что-то показать, поэтому, к сожалению, завтра у меня нет времени.(treffe Klara zeigen Zeit)',
    t1: 'Ich',
    t2: 'treffe',
    t3: 'morgen',
    t4: 'Klara',
    t5: ',',
    t6: 'sie',
    t7: 'will',
    t8: 'mir',
    t9: 'etwas',
    t10: 'zeigen',
    t11: ',',
    t12: 'ich',
    t13: 'habe',
    t14: 'morgen',
    t15: 'daher',
    t16: 'leider',
    t17: 'keine',
    t18: 'Zeit',
    t18: '.',
  },
  {
    t0: 'Он очень любит животных и хорошо их держит.(mag Tiere hält)',
    t1: 'Er',
    t2: 'mag',
    t3: 'Tiere',
    t4: 'sehr',
    t5: 'und',
    t6: 'hält',
    t7: 'sie',
    t8: 'gut',
    t9: '.',
  },
  {
    t0: 'Можете ли вы помочь мне найти ее?(Können helfen finden)',
    t1: 'Können',
    t2: 'Sie',
    t3: 'mir',
    t4: 'helfen',
    t5: ',',
    t6: 'sie',
    t7: 'zu',
    t8: 'finden',
    t9: '?',
  },
  {
    t0: 'Если она возьмет на себя вину, она будет передана ей.(Schuld trägt ihrer überführt)',
    t1: 'Wenn',
    t2: 'sie',
    t3: 'die',
    t4: 'Schuld',
    t5: 'trägt',
    t6: ',',
    t7: 'wird',
    t8: 'sie',
    t9: 'ihrer',
    t10: 'überführt',
    t11: '.',
  },
  {
    t0: 'Тебя будут помнить.(Man erinnern)',
    t1: 'Man',
    t2: 'wird',
    t3: 'sich',
    t4: 'deiner',
    t5: 'erinnern',
    t6: '.',
  },
  {
    t0: 'Они стыдятся ее.(schämen sich)',
    t1: 'Sie',
    t2: 'schämen',
    t3: 'sich',
    t4: 'ihrer',
    t5: '.',
  },
  {
    t0: 'Когда я умру, они будут чтить мою память.(tot gedenken)',
    t1: 'Wenn',
    t2: 'ich',
    t3: 'tot',
    t4: 'bin',
    t5: ',',
    t6: 'werden',
    t7: 'sie',
    t8: 'meiner',
    t9: 'gedenken',
    t10: '.',
  },

]
)
</script>

<style lang="scss" ></style>