<template lang="pug">
.container
	.page-title 
		h2 Possessivpronomen
	Content(:items='Possessiv')
</template>


<script setup>
import { ref } from 'vue';
import Content from '@/components/Content.vue'
const Possessiv = ref([
	[
		{ id: 1, marker: 'M', text: 'mein' },
		{ id: 2, marker: 'M', text: 'dein' },
		{ id: 3, marker: 'M', text: 'sein' },
		{ id: 4, marker: 'M', text: 'ihr' },
		{ id: 5, marker: 'M', text: 'unser' },
		{ id: 6, marker: 'M', text: 'euer' },
		{ id: 6, marker: 'M', text: 'ihr' },
		{ id: 6, marker: 'F', text: 'meine' },
		{ id: 6, marker: 'F', text: 'deine' },
		{ id: 6, marker: 'F', text: 'seine' },
		{ id: 6, marker: 'F', text: 'ihre' },
		{ id: 6, marker: 'F', text: 'unsere' },
		{ id: 6, marker: 'F', text: 'eure' },
		{ id: 6, marker: 'F', text: 'ihre' },
		{ id: 6, marker: 'N', text: 'mein' },
		{ id: 6, marker: 'N', text: 'dein' },
		{ id: 6, marker: 'N', text: 'sein' },
		{ id: 6, marker: 'N', text: 'ihr' },
		{ id: 6, marker: 'N', text: 'unser' },
		{ id: 6, marker: 'N', text: 'euer' },
		{ id: 6, marker: 'N', text: 'ihr' },
		{ id: 6, marker: 'P', text: 'meine' },
		{ id: 6, marker: 'P', text: 'deine' },
		{ id: 6, marker: 'P', text: 'seine' },
		{ id: 6, marker: 'P', text: 'ihre' },
		{ id: 6, marker: 'P', text: 'unsere' },
		{ id: 6, marker: 'P', text: 'eure' },
		{ id: 6, marker: 'P', text: 'ihre' },

	],
	[
		{ id: 1, marker: 'M', text: 'meinem ' },
		{ id: 2, marker: 'M', text: 'deinem' },
		{ id: 3, marker: 'M', text: 'seinem' },
		{ id: 4, marker: 'M', text: 'ihrem' },
		{ id: 5, marker: 'M', text: 'unserem' },
		{ id: 6, marker: 'M', text: 'euerem' },
		{ id: 6, marker: 'M', text: 'ihrem' },
		{ id: 6, marker: 'F', text: 'meiner' },
		{ id: 6, marker: 'F', text: 'deiner' },
		{ id: 6, marker: 'F', text: 'seiner' },
		{ id: 6, marker: 'F', text: 'ihrer' },
		{ id: 6, marker: 'F', text: 'unserer' },
		{ id: 6, marker: 'F', text: 'eurer' },
		{ id: 6, marker: 'F', text: 'ihrer' },
		{ id: 6, marker: 'N', text: 'meinem' },
		{ id: 6, marker: 'N', text: 'deinem' },
		{ id: 6, marker: 'N', text: 'seinem' },
		{ id: 6, marker: 'N', text: 'ihrem' },
		{ id: 6, marker: 'N', text: 'unserem' },
		{ id: 6, marker: 'N', text: 'euerem' },
		{ id: 6, marker: 'N', text: 'ihrem' },
		{ id: 6, marker: 'P', text: 'meinen' },
		{ id: 6, marker: 'P', text: 'deinen' },
		{ id: 6, marker: 'P', text: 'seinen' },
		{ id: 6, marker: 'P', text: 'ihren' },
		{ id: 6, marker: 'P', text: 'unseren' },
		{ id: 6, marker: 'P', text: 'euren' },
		{ id: 6, marker: 'P', text: 'ihren' },
	],
	[
		{ id: 1, marker: 'M', text: 'meinen ' },
		{ id: 2, marker: 'M', text: 'deinen' },
		{ id: 3, marker: 'M', text: 'seinen' },
		{ id: 4, marker: 'M', text: 'ihren' },
		{ id: 5, marker: 'M', text: 'unseren' },
		{ id: 6, marker: 'M', text: 'eueren' },
		{ id: 6, marker: 'M', text: 'ihren' },
		{ id: 6, marker: 'F', text: 'meine' },
		{ id: 6, marker: 'F', text: 'deine' },
		{ id: 6, marker: 'F', text: 'seine' },
		{ id: 6, marker: 'F', text: 'ihre' },
		{ id: 6, marker: 'F', text: 'unsere' },
		{ id: 6, marker: 'F', text: 'eure' },
		{ id: 6, marker: 'F', text: 'ihre' },
		{ id: 6, marker: 'N', text: 'mein' },
		{ id: 6, marker: 'N', text: 'dein' },
		{ id: 6, marker: 'N', text: 'sein' },
		{ id: 6, marker: 'N', text: 'ihr' },
		{ id: 6, marker: 'N', text: 'unser' },
		{ id: 6, marker: 'N', text: 'euer' },
		{ id: 6, marker: 'N', text: 'ihr' },
		{ id: 6, marker: 'P', text: 'meine' },
		{ id: 6, marker: 'P', text: 'deine' },
		{ id: 6, marker: 'P', text: 'seine' },
		{ id: 6, marker: 'P', text: 'ihre' },
		{ id: 6, marker: 'P', text: 'unsere' },
		{ id: 6, marker: 'P', text: 'eure' },
		{ id: 6, marker: 'P', text: 'ihre' },
	],
	[
		{ id: 1, marker: 'M', text: 'meines ' },
		{ id: 2, marker: 'M', text: 'deines' },
		{ id: 3, marker: 'M', text: 'seines' },
		{ id: 4, marker: 'M', text: 'ihres' },
		{ id: 5, marker: 'M', text: 'unseres' },
		{ id: 6, marker: 'M', text: 'eueres' },
		{ id: 6, marker: 'M', text: 'ihres' },
		{ id: 6, marker: 'F', text: 'meiner' },
		{ id: 6, marker: 'F', text: 'deiner' },
		{ id: 6, marker: 'F', text: 'seiner' },
		{ id: 6, marker: 'F', text: 'ihrer' },
		{ id: 6, marker: 'F', text: 'unserer' },
		{ id: 6, marker: 'F', text: 'eurer' },
		{ id: 6, marker: 'F', text: 'ihrer' },
		{ id: 6, marker: 'N', text: 'meines' },
		{ id: 6, marker: 'N', text: 'deines' },
		{ id: 6, marker: 'N', text: 'seines' },
		{ id: 6, marker: 'N', text: 'ihres' },
		{ id: 6, marker: 'N', text: 'unseres' },
		{ id: 6, marker: 'N', text: 'eueres' },
		{ id: 6, marker: 'N', text: 'ihres' },
		{ id: 6, marker: 'P', text: 'meiner' },
		{ id: 6, marker: 'P', text: 'deiner' },
		{ id: 6, marker: 'P', text: 'seiner' },
		{ id: 6, marker: 'P', text: 'ihrer' },
		{ id: 6, marker: 'P', text: 'unserer' },
		{ id: 6, marker: 'P', text: 'eurer' },
		{ id: 6, marker: 'P', text: 'ihrer' },
	]
]
)
</script>

<style lang="scss" ></style>