<template lang="pug">
.container
	.page-title 
		h2 Possessivpronomen
	Content(:items='Possessiv' :headers='Headers')
</template>


<script setup>
import { ref } from 'vue';
import Content from '@/components/Content.vue';
const Headers = ref([
	{ title: 'Nominativ' },
	{ title: 'Dativ' },
	{ title: 'Akkusativ' },
	{ title: 'Genitiv' },

]);
const Possessiv = ref([
	[
		{ id: 1, marker: 'M', text: 'mein' },
		{ id: 2, marker: 'M', text: 'dein' },
		{ id: 3, marker: 'M', text: 'sein' },
		{ id: 4, marker: 'M', text: 'ihr' },
		{ id: 5, marker: 'M', text: 'unser' },
		{ id: 6, marker: 'M', text: 'euer' },
		{ id: 7, marker: 'M', text: 'ihr' },
		{ id: 8, marker: 'F', text: 'meine' },
		{ id: 9, marker: 'F', text: 'deine' },
		{ id: 10, marker: 'F', text: 'seine' },
		{ id: 11, marker: 'F', text: 'ihre' },
		{ id: 12, marker: 'F', text: 'unsere' },
		{ id: 13, marker: 'F', text: 'eure' },
		{ id: 14, marker: 'F', text: 'ihre' },
		{ id: 15, marker: 'N', text: 'mein' },
		{ id: 16, marker: 'N', text: 'dein' },
		{ id: 17, marker: 'N', text: 'sein' },
		{ id: 18, marker: 'N', text: 'ihr' },
		{ id: 19, marker: 'N', text: 'unser' },
		{ id: 20, marker: 'N', text: 'euer' },
		{ id: 21, marker: 'N', text: 'ihr' },
		{ id: 22, marker: 'P', text: 'meine' },
		{ id: 23, marker: 'P', text: 'deine' },
		{ id: 24, marker: 'P', text: 'seine' },
		{ id: 25, marker: 'P', text: 'ihre' },
		{ id: 26, marker: 'P', text: 'unsere' },
		{ id: 27, marker: 'P', text: 'eure' },
		{ id: 28, marker: 'P', text: 'ihre' },

	],
	[
		{ id: 1, marker: 'M', text: 'meinem ' },
		{ id: 2, marker: 'M', text: 'deinem' },
		{ id: 3, marker: 'M', text: 'seinem' },
		{ id: 4, marker: 'M', text: 'ihrem' },
		{ id: 5, marker: 'M', text: 'unserem' },
		{ id: 6, marker: 'M', text: 'euerem' },
		{ id: 7, marker: 'M', text: 'ihrem' },
		{ id: 8, marker: 'F', text: 'meiner' },
		{ id: 9, marker: 'F', text: 'deiner' },
		{ id: 10, marker: 'F', text: 'seiner' },
		{ id: 11, marker: 'F', text: 'ihrer' },
		{ id: 12, marker: 'F', text: 'unserer' },
		{ id: 13, marker: 'F', text: 'eurer' },
		{ id: 14, marker: 'F', text: 'ihrer' },
		{ id: 15, marker: 'N', text: 'meinem' },
		{ id: 16, marker: 'N', text: 'deinem' },
		{ id: 17, marker: 'N', text: 'seinem' },
		{ id: 18, marker: 'N', text: 'ihrem' },
		{ id: 19, marker: 'N', text: 'unserem' },
		{ id: 20, marker: 'N', text: 'euerem' },
		{ id: 21, marker: 'N', text: 'ihrem' },
		{ id: 22, marker: 'P', text: 'meinen' },
		{ id: 23, marker: 'P', text: 'deinen' },
		{ id: 24, marker: 'P', text: 'seinen' },
		{ id: 25, marker: 'P', text: 'ihren' },
		{ id: 26, marker: 'P', text: 'unseren' },
		{ id: 27, marker: 'P', text: 'euren' },
		{ id: 28, marker: 'P', text: 'ihren' },
	],
	[
		{ id: 1, marker: 'M', text: 'meinen ' },
		{ id: 2, marker: 'M', text: 'deinen' },
		{ id: 3, marker: 'M', text: 'seinen' },
		{ id: 4, marker: 'M', text: 'ihren' },
		{ id: 5, marker: 'M', text: 'unseren' },
		{ id: 6, marker: 'M', text: 'eueren' },
		{ id: 7, marker: 'M', text: 'ihren' },
		{ id: 8, marker: 'F', text: 'meine' },
		{ id: 9, marker: 'F', text: 'deine' },
		{ id: 10, marker: 'F', text: 'seine' },
		{ id: 11, marker: 'F', text: 'ihre' },
		{ id: 12, marker: 'F', text: 'unsere' },
		{ id: 13, marker: 'F', text: 'eure' },
		{ id: 14, marker: 'F', text: 'ihre' },
		{ id: 15, marker: 'N', text: 'mein' },
		{ id: 16, marker: 'N', text: 'dein' },
		{ id: 17, marker: 'N', text: 'sein' },
		{ id: 18, marker: 'N', text: 'ihr' },
		{ id: 19, marker: 'N', text: 'unser' },
		{ id: 20, marker: 'N', text: 'euer' },
		{ id: 21, marker: 'N', text: 'ihr' },
		{ id: 22, marker: 'P', text: 'meine' },
		{ id: 23, marker: 'P', text: 'deine' },
		{ id: 24, marker: 'P', text: 'seine' },
		{ id: 25, marker: 'P', text: 'ihre' },
		{ id: 26, marker: 'P', text: 'unsere' },
		{ id: 27, marker: 'P', text: 'eure' },
		{ id: 28, marker: 'P', text: 'ihre' },
	],
	[
		{ id: 1, marker: 'M', text: 'meines ' },
		{ id: 2, marker: 'M', text: 'deines' },
		{ id: 3, marker: 'M', text: 'seines' },
		{ id: 4, marker: 'M', text: 'ihres' },
		{ id: 5, marker: 'M', text: 'unseres' },
		{ id: 6, marker: 'M', text: 'eueres' },
		{ id: 7, marker: 'M', text: 'ihres' },
		{ id: 8, marker: 'F', text: 'meiner' },
		{ id: 9, marker: 'F', text: 'deiner' },
		{ id: 10, marker: 'F', text: 'seiner' },
		{ id: 11, marker: 'F', text: 'ihrer' },
		{ id: 12, marker: 'F', text: 'unserer' },
		{ id: 13, marker: 'F', text: 'eurer' },
		{ id: 14, marker: 'F', text: 'ihrer' },
		{ id: 15, marker: 'N', text: 'meines' },
		{ id: 16, marker: 'N', text: 'deines' },
		{ id: 17, marker: 'N', text: 'seines' },
		{ id: 18, marker: 'N', text: 'ihres' },
		{ id: 19, marker: 'N', text: 'unseres' },
		{ id: 20, marker: 'N', text: 'eueres' },
		{ id: 21, marker: 'N', text: 'ihres' },
		{ id: 22, marker: 'P', text: 'meiner' },
		{ id: 23, marker: 'P', text: 'deiner' },
		{ id: 24, marker: 'P', text: 'seiner' },
		{ id: 25, marker: 'P', text: 'ihrer' },
		{ id: 26, marker: 'P', text: 'unserer' },
		{ id: 27, marker: 'P', text: 'eurer' },
		{ id: 28, marker: 'P', text: 'ihrer' },
	]
]
)
</script>

<style lang="scss" ></style>