<template lang="pug">
.container
	.page-title 
		h2 Zeigepronomen
	Content(:items='Zeigepronomen' :headers='Headers')
</template>


<script setup>
import { ref } from 'vue';
import Content from '@/components/Content.vue';
const Headers = ref([
	{ title: 'Nominativ' },
	{ title: 'Dativ' },
	{ title: 'Akkusativ' },
	{ title: 'Genitiv' },

]);
const Zeigepronomen = ref([
	[
		{ id: 1, marker: 'M', text: 'dieser' },
		{ id: 2, marker: 'M', text: 'jener' },
		{ id: 3, marker: 'M', text: 'derselbe' },
		{ id: 4, marker: 'M', text: 'solch ein' },
		{ id: 5, marker: 'M', text: 'eine solche' },
		{ id: 6, marker: 'M', text: 'so eine' },
		{ id: 8, marker: 'F', text: 'die' },
		{ id: 9, marker: 'F', text: 'diese' },
		{ id: 10, marker: 'F', text: 'jene' },
		{ id: 11, marker: 'F', text: 'diejenige' },
		{ id: 12, marker: 'F', text: 'dieselbe' },
		{ id: 13, marker: 'F', text: 'solch eine' },
		{ id: 14, marker: 'F', text: 'eine solche' },
		{ id: 14, marker: 'F', text: 'so eine' },
		{ id: 15, marker: 'N', text: 'das' },
		{ id: 16, marker: 'N', text: 'dieses' },
		{ id: 17, marker: 'N', text: 'jenes' },
		{ id: 18, marker: 'N', text: 'dasjenige' },
		{ id: 19, marker: 'N', text: 'dasselbe' },
		{ id: 20, marker: 'N', text: 'solch ein' },
		{ id: 21, marker: 'N', text: 'ein solches' },
		{ id: 21, marker: 'N', text: 'so ein' },
		{ id: 22, marker: 'P', text: 'die' },
		{ id: 23, marker: 'P', text: 'diese ' },
		{ id: 24, marker: 'P', text: 'jene' },
		{ id: 25, marker: 'P', text: 'diejenigen' },
		{ id: 26, marker: 'P', text: 'dieselben' },
		{ id: 27, marker: 'P', text: 'solche' },
		{ id: 28, marker: 'P', text: 'ihre' },

	],
	[
		{ id: 1, marker: 'M', text: 'dem' },
		{ id: 2, marker: 'M', text: 'diesem' },
		{ id: 3, marker: 'M', text: 'jenem' },
		{ id: 4, marker: 'M', text: 'demjenigen' },
		{ id: 5, marker: 'M', text: 'demselben' },
		{ id: 6, marker: 'M', text: 'solch einem' },
		{ id: 7, marker: 'M', text: 'einem solchen' },
		{ id: 8, marker: 'M', text: 'so einem' },
		{ id: 9, marker: 'F', text: 'der' },
		{ id: 10, marker: 'F', text: 'dieser' },
		{ id: 11, marker: 'F', text: 'jener' },
		{ id: 12, marker: 'F', text: 'derjenigen' },
		{ id: 13, marker: 'F', text: 'derselben' },
		{ id: 14, marker: 'F', text: 'solch einer' },
		{ id: 15, marker: 'F', text: 'einer solchen' },
		{ id: 16, marker: 'F', text: 'so einer' },
		{ id: 17, marker: 'N', text: 'dem' },
		{ id: 18, marker: 'N', text: 'diesem' },
		{ id: 19, marker: 'N', text: 'jenem' },
		{ id: 20, marker: 'N', text: 'demjenigen' },
		{ id: 21, marker: 'N', text: 'demselben' },
		{ id: 22, marker: 'N', text: 'solch einem' },
		{ id: 23, marker: 'N', text: 'einem solchen' },
		{ id: 24, marker: 'N', text: 'so einem' },
		{ id: 25, marker: 'P', text: 'den' },
		{ id: 26, marker: 'P', text: 'diesen' },
		{ id: 27, marker: 'P', text: 'jenen' },
		{ id: 28, marker: 'P', text: 'denjenigen' },
		{ id: 29, marker: 'P', text: 'denselben' },
		{ id: 30, marker: 'P', text: 'solchen' },
	],
	[
		{ id: 1, marker: 'M', text: 'den' },
		{ id: 2, marker: 'M', text: 'diesen' },
		{ id: 3, marker: 'M', text: 'jenen' },
		{ id: 4, marker: 'M', text: 'denjenigen' },
		{ id: 5, marker: 'M', text: 'denselben' },
		{ id: 6, marker: 'M', text: 'einen' },
		{ id: 7, marker: 'M', text: 'einen solhen' },
		{ id: 8, marker: 'M', text: 'so einen' },
		{ id: 9, marker: 'F', text: 'die' },
		{ id: 10, marker: 'F', text: 'diese' },
		{ id: 11, marker: 'F', text: 'jene' },
		{ id: 12, marker: 'F', text: 'diejenige' },
		{ id: 13, marker: 'F', text: 'dieselbe' },
		{ id: 14, marker: 'F', text: 'Solch eine' },
		{ id: 15, marker: 'F', text: 'Eine solche' },
		{ id: 16, marker: 'F', text: 'so eine' },
		{ id: 17, marker: 'N', text: 'das' },
		{ id: 18, marker: 'N', text: 'dieses' },
		{ id: 19, marker: 'N', text: 'jenes' },
		{ id: 20, marker: 'N', text: 'dasselbe' },
		{ id: 21, marker: 'N', text: 'ein' },
		{ id: 22, marker: 'N', text: 'ein solches' },
		{ id: 23, marker: 'N', text: 'so ein' },
		{ id: 24, marker: 'P', text: 'die' },
		{ id: 25, marker: 'P', text: 'diese' },
		{ id: 26, marker: 'P', text: 'jene' },
		{ id: 27, marker: 'P', text: 'diejenigen' },
		{ id: 28, marker: 'P', text: 'dieselben' },
		{ id: 29, marker: 'P', text: 'solche' },
	],
	[
		{ id: 1, marker: 'M', text: 'des' },
		{ id: 2, marker: 'M', text: 'dieses' },
		{ id: 3, marker: 'M', text: 'jenes' },
		{ id: 4, marker: 'M', text: 'desjenigen' },
		{ id: 5, marker: 'M', text: 'desselben' },
		{ id: 6, marker: 'M', text: 'solch eines' },
		{ id: 7, marker: 'M', text: 'eines solhen' },
		{ id: 8, marker: 'M', text: 'so eines' },
		{ id: 9, marker: 'F', text: 'der' },
		{ id: 10, marker: 'F', text: 'dieser' },
		{ id: 11, marker: 'F', text: 'jener' },
		{ id: 12, marker: 'F', text: 'derjenigen' },
		{ id: 13, marker: 'F', text: 'derselben' },
		{ id: 14, marker: 'F', text: 'solch einer' },
		{ id: 15, marker: 'F', text: 'einer solchen' },
		{ id: 16, marker: 'F', text: 'so einer' },
		{ id: 17, marker: 'N', text: 'des' },
		{ id: 18, marker: 'N', text: 'dieses' },
		{ id: 19, marker: 'N', text: 'jenes' },
		{ id: 20, marker: 'N', text: 'desjenigen' },
		{ id: 21, marker: 'N', text: 'desselben' },
		{ id: 22, marker: 'N', text: 'solch eines' },
		{ id: 23, marker: 'N', text: 'eines solchen' },
		{ id: 24, marker: 'N', text: 'so eines' },
		{ id: 25, marker: 'P', text: 'der' },
		{ id: 26, marker: 'P', text: 'dieser' },
		{ id: 27, marker: 'P', text: 'jener' },
		{ id: 28, marker: 'P', text: 'derjenigen' },
		{ id: 29, marker: 'P', text: 'deselben' },
		{ id: 30, marker: 'P', text: 'solher' },
	]

]
)
</script>

<style lang="scss" ></style>